# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000v2k8ed\tmp\build\80754af9\rsync-recipes\pyrsistent-0.14.11-python_3.7-c_compiler_vs2017-on-winbuilder, last modified Mon Mar 11 13:18:22 2019
# ------------------------------------------------

package:
    name: pyrsistent
    version: 0.14.11
source:
    sha256: 3ca82748918eb65e2d89f222b702277099aca77e34843c5eb9d52451173970e2
    url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-0.14.11.tar.gz
build:
    number: '0'
    script: C:\ci\pyrsistent_1552336409048\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed -vvv
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - atomicwrites 1.3.0 py_0
        - attrs 19.1.0 py_0
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - colorama 0.4.1 py37_0
        - more-itertools 5.0.0 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - pluggy 0.9.0 py37_0
        - py 1.8.0 py37_0
        - pytest 4.3.0 py37_0
        - pytest-runner 4.2 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - six
        - vc >=14.1,<15.0a0
test:
    imports:
        - pyrsistent
    requires:
        - hypothesis
        - pytest
about:
    home: http://github.com/tobgu/pyrsistent/
    license: MIT
    license_family: MIT
    license_file: LICENCE.mit
    summary: Persistent/Functional/Immutable data structures
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
