# This file created by conda-build 3.17.6
# meta.yaml template originally from:
# C:\ci\containers\00002gc3h3a\tmp\build\80754af9\rsync-recipes\mkl_fft-1.0.10-cxx_compiler_vs2017-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Fri Jan 11 14:22:55 2019
# ------------------------------------------------

package:
    name: mkl_fft
    version: 1.0.10
source:
    sha256: 652321a6816f22c8c85f492c933e0b5c395a44b14d63d630981bc24d2bd7a742
    url: https://github.com/IntelPython/mkl_fft/archive/v1.0.10.tar.gz
build:
    number: '0'
    script: C:\\ci\\mkl_fft_1547238522537\\_h_env\\python.exe setup.py build install
        --single-version-externally-managed --record=record.txt
    string: py37h14836fe_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - cython 0.29.2 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - mkl 2019.1 144
        - mkl-devel 2019.1 145
        - mkl-include 2019.1 144
        - numpy-base 1.11.3 py37hc3f5095_12
        - numpy-devel 1.11.3 py37h4ba5984_12
        - openssl 1.1.1a he774522_0
        - python 3.7.2 h8c8aaf0_0
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - blas 1.0 mkl
        - mkl >=2019.1,<2020.0a0
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    commands:
        - nosetests -v mkl_fft
    imports:
        - mkl_fft
        - mkl_fft._numpy_fft
        - mkl_fft._scipy_fft
    requires:
        - nose
about:
    description: NumPy-based implementation of Fast Fourier Transform using Intel
        (R) Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex
        FFT on arrays of single and double precision with arbitrary memory layout,
        so long as array strides are multiples of its itemsize.
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R)
        Math Kernel Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
