# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\nbformat-feedstock\recipe, last modified Tue Jul  3 15:51:00 2018
# ------------------------------------------------

package:
    name: nbformat
    version: 4.4.0
source:
    fn: nbformat-4.4.0.tar.gz
    sha256: f7494ef0df60766b7cabe0a3651556345a963b74dbc16bc7c18479041170d402
    url: https://pypi.io/packages/source/n/nbformat/nbformat-4.4.0.tar.gz
build:
    entry_points:
        - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance
    number: '0'
    script: pip install --no-deps .
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - ipython_genutils
        - jsonschema >=2.4,!=2.5.0
        - jupyter_core
        - python >=3.7,<3.8.0a0
        - traitlets >=4.1
test:
    commands:
        - jupyter-trust -h
    imports:
        - nbformat
about:
    description: 'nbformat contains the reference implementation of the Jupyter Notebook

        format, and Python APIs for working with notebooks.

        '
    dev_url: https://github.com/jupyter/nbformat
    doc_url: http://nbformat.readthedocs.org
    home: http://jupyter.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: The reference implementation of the Jupyter Notebook format
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - mpacer
        - ocefpaf
        - pelson
        - takluyver
