# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000004ll47g\tmp\build\80754af9\rsync-recipes\zeromq-4.3.1-c_compiler_vs2017-vc_14-cxx_compiler_vs2017-on-winbuilder, last modified Fri Feb  1 06:49:37 2019
# ------------------------------------------------

package:
    name: zeromq
    version: 4.3.1
source:
    patches:
        - 0001-Files-required-to-include-ClangFormat-are-missing.patch
        - 0002-Install-ZeroMQConfig.cmake-on-Windows-to-same-place-.patch
        - 0003-SLES11-Hackily-avoid-pthread_set_name_np-on-linux.patch
        - 0005-osx-test.patch
    sha256: bcbabe1e2c7d0eec4ed612e10b94b112dd5f06fcefa994a0c79a45d835cd21eb
    url: https://github.com/zeromq/libzmq/releases/download/v4.3.1/zeromq-4.3.1.tar.gz
build:
    number: '3'
    run_exports:
        - zeromq >=4.3.1,<4.4.0a0
    string: h33f27b4_3
requirements:
    build:
        - cmake 3.12.2 he025d50_0
        - git 2.20.1 h6bb4b03_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - libsodium 1.0.16 h9d3ae62_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - libsodium >=1.0.16,<1.0.17.0a0
        - vc >=14.1,<15.0a0
test:
    commands:
        - if exist %LIBRARY_LIB%\libzmq-mt-s-4_3_1.lib (exit 0) else (exit 1)
        - if exist %LIBRARY_BIN%\libzmq-mt-4_3_1.dll (exit 0) else (exit 1)
        - if exist %LIBRARY_LIB%\libzmq-mt-4_3_1.lib (exit 0) else (exit 1)
        - if exist %LIBRARY_BIN%\libzmq.dll (exit 0) else (exit 1)
        - if exist %LIBRARY_LIB%\libzmq.lib (exit 0) else (exit 1)
        - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfig.cmake (exit 0) else
            (exit 1)
        - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfigVersion.cmake (exit 0)
            else (exit 1)
about:
    home: http://zeromq.org
    license: LGPL 3
    summary: A high-performance asynchronous messaging library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - minrk
