# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000029cv5k5\tmp\build\80754af9\rsync-recipes\attrs-19.1.0-python_3.7-on-winbuilder, last modified Fri Mar 22 13:25:44 2019
# ------------------------------------------------

package:
    name: attrs
    version: 19.1.0
source:
    fn: attrs-19.1.0.tar.gz
    sha256: f0b870f674851ecbfbbbd364d6b5cbdff9dcedbc7f3f5e18a6891057f21fe399
    url: https://pypi.io/packages/source/a/attrs/attrs-19.1.0.tar.gz
build:
    noarch: false
    number: '1'
    script: python -m pip install . --no-deps --ignore-installed
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - attr
about:
    description: 'attrs is the Python package that will bring back the joy of writing

        classes by relieving you from the drudgery of implementing object

        protocols (aka dunder methods). Its main goal is to help you to write

        concise and correct software without slowing down your code. For that, it

        gives you a class decorator and a way to declaratively define the

        attributes on that class:

        '
    dev_url: https://github.com/python-attrs/attrs
    doc_url: https://attrs.readthedocs.io/en/stable/
    home: https://attrs.readthedocs.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: attrs is the Python package that will bring back the joy of writing classes
        by relieving you from the drudgery of implementing object protocols (aka dunder
        methods).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
        - jochym
        - licode
        - nicoddemus
