# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000001qof8g\tmp\build\80754af9\rsync-recipes\scipy-1.2.1-vc_14-python_3.7-fortran_compiler_version_2019.0.0-blas_impl_mkl-on-winbuilder, last modified Wed Feb 20 11:03:28 2019
# ------------------------------------------------

package:
    name: scipy
    version: 1.2.1
source:
    patches:
        - 0008-xfail-last-pcol-test.patch
        - 0009-Disable-test_splrep_errors.patch
    sha256: d4b9c1c1dee37ffd1653fd62ea52587212d3b1570c927f16719fd7c4077c0d0a
    url: https://github.com/scipy/scipy/archive/v1.2.1.tar.gz
build:
    number: '0'
    string: py37h29ff71c_0
requirements:
    build:
        - intel-fortran_win-64 2019.0.0 hf4e3f46_1
    host:
        - blas 1.0 mkl
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - cython 0.29.5 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - mkl 2019.1 144
        - mkl-devel 2019.1 145
        - mkl-include 2019.1 144
        - numpy-base 1.11.3 py37hc3f5095_12
        - numpy-devel 1.11.3 py37h4ba5984_12
        - openssl 1.1.1a he774522_0
        - python 3.7.2 h8c8aaf0_2
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - blas 1.0 mkl
        - icc_rt >=2019.0.0
        - mkl >=2019.1,<2020.0a0
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
test:
    requires:
        - mpmath
        - pytest <4
about:
    description: 'SciPy is a Python-based ecosystem of open-source software for mathematics,

        science, and engineering.

        '
    dev_url: https://github.com/scipy/scipy
    doc_url: http://www.scipy.org/docs.html
    home: http://www.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Scientific Library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - rgommers
