# This file created by conda-build 3.17.6
# ------------------------------------------------

package:
    name: liblief
    version: 0.9.0
source:
    -   fn: lief-0.9.0.tar.gz
        patches:
            - 0001-Allow-building-from-released-tarball.patch
            - 0002-MSVC-Add-bigobj-flag.patch
            - 0003-Export-LIEF-Object-and-LIEF-MachO-DataCodeEntry-clas.patch
            - 0004-MachO-Fix-has_dynamic_symbol_command.patch
            - 0005-Link-Python-extension-module-to-shared-LIEF-library.patch
        sha256: 8f1a12d69d9f6bd8404d4f5809549d1c7f3138cacf3bccd1192cb4f46bfb9eb7
        url: https://github.com/lief-project/LIEF/archive/0.9.0.tar.gz
build:
    number: 2
    run_exports:
        - liblief >=0.9.0,<0.10.0a0
    string: ha925a31_2
requirements:
    build:
        - cmake 3.12.2 he025d50_0
        - git 2.19.1 h6bb4b03_0
        - jom 1.1.2 h3bd88b9_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - vc >=14.1,<15.0a0
test:
    files:
        - tests
    requires:
        - cmake
        - jom
        - vs2017_win-64
    script: run_test_liblief.sh
about:
    description: 'It turns out that many projects need to parse executable formats
        and they usually re-implement

        their own parser. Moreover these parsers are usually bound to one language.

        LIEF attempts to fill this void.

        '
    doc_source_url: https://github.com/lief-project/LIEF/tree/master/doc
    doc_url: https://lief.quarkslab.com/doc/stable/index.html
    home: https://lief.quarkslab.com/
    license: Apache 2.0
    license_family: Apache
    summary: A cross platform library to parse, modify and abstract ELF, PE and MachO
        formats.
extra:
    copy_test_source_files: true
    final: true
