# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# C:\ci\containers\00003r3dp0i\tmp\build\80754af9\rsync-recipes\bitarray-0.8.3-python_3.7-c_compiler_vs2015-on-winbuilder, last modified Wed Jul 25 08:18:35 2018
# ------------------------------------------------

package:
    name: bitarray
    version: 0.8.3
source:
    fn: bitarray-0.8.3.tar.gz
    sha256: 050cd30b810ddb3aa941e7ddfbe0d8065e793012d0a88cb5739ec23624b9895e
    url: https://pypi.io/packages/source/b/bitarray/bitarray-0.8.3.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py37hfa6e2cd_0
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc 14.*
test:
    imports:
        - bitarray
about:
    description: 'Bitarray provides an object type which efficiently represents an
        array of

        booleans. Bitarrays are sequence types that behave very similarly

        to usual lists. All functionality is implemented in C.

        '
    dev_url: https://github.com/ilanschnell/bitarray
    doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
    home: https://github.com/ilanschnell/bitarray
    license: PSF
    summary: efficient arrays of booleans -- C extension
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
