# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000001qofc2\tmp\build\80754af9\rsync-recipes\prometheus_client-0.6.0-python_3.7-on-winbuilder, last modified Mon Feb 25 17:14:51 2019
# ------------------------------------------------

package:
    name: prometheus_client
    version: 0.6.0
source:
    sha256: d1f99fbc91d3191d7dd78808665627fd3df0a34b52e000538cc18e39789a2cd7
    url: https://github.com/prometheus/client_python/archive/v0.6.0.tar.gz
build:
    noarch: false
    number: '0'
    script: C:\ci\prometheus_client_1551195242277\_h_env\python.exe -m pip install
        . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - prometheus_client
        - prometheus_client.bridge
about:
    home: https://github.com/prometheus/client_python
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Python client for the Prometheus monitoring system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jessicaaustin
        - kwilcox
        - ocefpaf
