# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003cheg68\tmp\build\80754af9\rsync-recipes\ipython-7.4.0-python_3.7-on-winbuilder, last modified Mon Mar 25 09:17:35 2019
# ------------------------------------------------

package:
    name: ipython
    version: 7.4.0
source:
    sha256: b038baa489c38f6d853a3cfc4c635b0cda66f2864d136fe8f40c1a6e334e2a6b
    url: https://pypi.io/packages/source/i/ipython/ipython-7.4.0.tar.gz
build:
    entry_points:
        - iptest = IPython.testing.iptestcontroller:main
        - iptest3 = IPython.testing.iptestcontroller:main
        - ipython = IPython:start_ipython
        - ipython3 = IPython:start_ipython
    number: '0'
    script: C:\ci\ipython_1553524951561\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed -vvv
    string: py37h39e3cac_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - backcall
        - colorama
        - decorator
        - jedi >=0.10
        - pickleshare
        - prompt_toolkit >=2.0.0
        - pygments
        - python >=3.7,<3.8.0a0
        - traitlets >=4.2
test:
    commands:
        - ipython -h
        - ipython3 -h
    imports:
        - IPython
        - IPython.core
        - IPython.core.magics
        - IPython.core.tests
        - IPython.extensions
        - IPython.extensions.tests
        - IPython.external
        - IPython.external.decorators
        - IPython.lib
        - IPython.lib.tests
        - IPython.sphinxext
        - IPython.terminal
        - IPython.terminal.pt_inputhooks
        - IPython.terminal.tests
        - IPython.testing
        - IPython.testing.plugin
        - IPython.testing.tests
        - IPython.utils
        - IPython.utils.tests
    requires:
        - ipykernel
        - matplotlib
        - nbformat
        - nose>=0.10.1
        - numpy
        - pygments
        - requests
        - testpath
about:
    description: 'IPython provides a rich architecture for interactive computing with

        a powerful interactive shell, a kernel for Jupyter, high performance

        tools for parallel computing, and more.

        '
    dev_url: https://github.com/ipython/ipython
    doc_url: https://ipython.readthedocs.io/
    home: https://ipython.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: 'IPython: Productive Interactive Computing'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - ellisonbg
        - fperez
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
