# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\sphinxcontrib-websupport-feedstock\recipe, last modified Tue Jul  3 15:55:27 2018
# ------------------------------------------------

package:
    name: sphinxcontrib-websupport
    version: 1.1.0
source:
    fn: sphinxcontrib-websupport-1.1.0.tar.gz
    sha256: 9de47f375baf1ea07cdb3436ff39d7a9c76042c10a769c52353ec46e4e8fc3b9
    url: https://pypi.io/packages/source/s/sphinxcontrib-websupport/sphinxcontrib-websupport-1.1.0.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_1
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - sphinxcontrib 1.0 py37_1
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - sphinxcontrib
test:
    imports:
        - sphinxcontrib
about:
    description: 'sphinxcontrib-websupport provides a Python API to easily integrate

        Sphinx documentation into your Web application

        '
    dev_url: https://github.com/sphinx-doc/sphinxcontrib-websupport
    doc_url: http://www.sphinx-doc.org/en/stable/
    home: https://pypi.python.org/pypi/sphinxcontrib-websupport
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Sphinx API for Web Apps
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chohner
