# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\pyreadline-feedstock\recipe, last modified Tue Jul  3 15:53:22 2018
# ------------------------------------------------

package:
    name: pyreadline
    version: '2.1'
source:
    fn: pyreadline-2.1.zip
    sha256: 4530592fc2e85b25b1a9f79664433da09237c1a270e4d78ea5aa3a2c7229e2d1
    url: https://pypi.io/packages/source/p/pyreadline/pyreadline-2.1.zip
build:
    number: '1'
    script: python setup.py install
    string: py37_1
requirements:
    host:
        - python 3.7.0 hea74fb7_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - pyreadline
        - pyreadline.clipboard
        - pyreadline.console
        - pyreadline.keysyms
        - pyreadline.lineeditor
        - pyreadline.modes
about:
    description: 'The pyreadline package is a python implementation of GNU readline
        functionality

        it is based on the ctypes based UNC readline package by Gary Bishop. It is
        not

        complete. It has been tested for use with windows 2000 and windows xp.

        '
    dev_url: https://github.com/pyreadline/pyreadline
    doc_url: http://pythonhosted.org/pyreadline/
    home: http://ipython.org/pyreadline
    license: BSD 3-Clause
    license_family: BSD
    license_file: doc/COPYING
    summary: A python implmementation of GNU readline.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astaric
