# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\nose-feedstock\recipe, last modified Tue Jul  3 15:51:15 2018
# ------------------------------------------------

package:
    name: nose
    version: 1.3.7
source:
    fn: nose-1.3.7.tar.gz
    md5: 4d3ad0ff07b61373d2cefc89c5d0b20b
    patches:
        - win-rmentry.patch
    url: https://pypi.io/packages/source/n/nose/nose-1.3.7.tar.gz
build:
    entry_points:
        - nosetests = nose:run_exit
    number: '2'
    string: py37_2
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - nosetests -h
    imports:
        - nose
        - pkg_resources
about:
    description: 'NOTE: Nose has been in maintenance mode for the past several years
        and will

        likely cease without a new person/team to take over maintainership. New

        projects should consider using Nose2, py.test, or just plain

        unittest/unittest2.

        '
    dev_url: https://github.com/nose-devs/nose/
    doc_source_url: https://github.com/nose-devs/nose/blob/master/doc/index.rst
    doc_url: https://nose.readthedocs.org
    home: http://readthedocs.org/docs/nose/
    license: LGPL-2.1
    license_file: lgpl.txt
    summary: Nose extends unittest to make testing easier
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - scopatz
