# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# C:\ci\containers\000015him7j\tmp\build\80754af9\rsync-recipes\h5py-2.9.0-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Fri Dec 21 10:57:41 2018
# ------------------------------------------------

package:
    name: h5py
    version: 2.9.0
source:
    sha256: 49d593c07a3a4cb87ed421f502e34368b98282a4ac6d4388379aab80b11c7924
    url: https://github.com/h5py/h5py/archive/2.9.0.tar.gz
build:
    number: '0'
    string: py37h5e291fa_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - cython 0.29.2 py37ha925a31_0
        - hdf5 1.10.4 h7ebc959_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-pkg-config 0.29.1 2
        - mkl 2019.1 144
        - msys2-conda-epoch 20160418 1
        - numpy-base 1.11.3 py37hc3f5095_12
        - numpy-devel 1.11.3 py37h4ba5984_12
        - openssl 1.1.1a he774522_0
        - pip 18.1 py37_0
        - pkgconfig 1.4.0 py37_0
        - python 3.7.1 h8c8aaf0_6
        - setuptools 40.6.3 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - hdf5 >=1.10.4,<1.10.5.0a0
        - numpy >=1.11.3,<2.0a0
        - pyreadline
        - python >=3.7,<3.8.0a0
        - six
        - vc >=14.1,<15.0a0
test:
    imports:
        - h5py
about:
    description: 'H5py uses straightforward NumPy and Python metaphors, like dictionary
        and

        NumPy array syntax.

        '
    dev_url: https://github.com/h5py/h5py
    doc_url: http://docs.h5py.org
    home: http://www.h5py.org/
    license: BSD-3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - pitrou
        - tacaswell
