# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002g6vms3\tmp\build\80754af9\rsync-recipes\pyyaml-5.1-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Mon Mar 18 10:54:36 2019
# ------------------------------------------------

package:
    name: pyyaml
    version: '5.1'
source:
    patches:
        - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
    sha256: 436bc774ecf7c103814098159fbb84c2715d25980175292c648f2da143909f95
    url: https://pypi.io/packages/source/P/PyYAML/PyYAML-5.1.tar.gz
build:
    number: '0'
    script:
        - python setup.py --with-libyaml build_ext --include-dirs="%LIBRARY_INC%"
            --library-dirs="%LIBRARY_LIB%"
        - python setup.py install
        - python setup.py test
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - cython 0.29.6 py37ha925a31_0
        - openssl 1.1.1b he774522_1
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
        - yaml 0.1.7 hc54c509_2
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - yaml >=0.1.7,<0.2.0a0
test:
    imports:
        - _yaml
        - yaml
about:
    description: 'YAML is a data serialization format designed for human readability
        and interaction with

        scripting languages.

        '
    dev_url: https://github.com/yaml/pyyaml
    doc_source_url: http://pyyaml.org/browser/pyyaml/trunk/README
    doc_url: http://pyyaml.org/wiki/PyYAMLDocumentation
    home: http://pyyaml.org/wiki/PyYAML
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: YAML parser and emitter for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
