# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000001qofbt\tmp\build\80754af9\rsync-recipes\parso-0.3.4-python_3.7-on-winbuilder, last modified Mon Feb 25 17:14:07 2019
# ------------------------------------------------

package:
    name: parso
    version: 0.3.4
source:
    fn: parso-0.3.4.tar.gz
    sha256: 68406ebd7eafe17f8e40e15a84b56848eccbf27d7c1feb89e93d8fca395706db
    url: https://pypi.io/packages/source/p/parso/parso-0.3.4.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - parso
        - parso.pgen2
        - parso.python
about:
    description: 'Parso is a Python parser that supports error recovery and round-trip
        parsing for different Python versions (in multiple Python versions).

        Parso is also able to list multiple syntax errors in your python file.

        '
    dev_url: https://github.com/davidhalter/parso
    doc_url: https://parso.readthedocs.io/en/latest/
    home: https://github.com/davidhalter/parso
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: A Python Parser
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - iron0012
        - synapticarbors
