# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000v2k8cf\tmp\build\80754af9\rsync-recipes\distributed-1.26.0-python_3.7-on-winbuilder, last modified Thu Mar  7 06:57:18 2019
# ------------------------------------------------

package:
    name: distributed
    version: 1.26.0
source:
    sha256: b9ffc4c28eb7a6639b15fbb84cea847693b6f9ce7e71f3e2a3e3272467b5b0b8
    url: https://pypi.io/packages/source/d/distributed/distributed-1.26.0.tar.gz
build:
    entry_points:
        - dask-mpi=distributed.cli.dask_mpi:go
        - dask-remote=distributed.cli.dask_remote:go
        - dask-scheduler=distributed.cli.dask_scheduler:go
        - dask-ssh=distributed.cli.dask_ssh:go
        - dask-submit=distributed.cli.dask_submit:go
        - dask-worker=distributed.cli.dask_worker:go
    number: '1'
    script: C:\ci\distributed_1551972041997\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1b he774522_0
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - click >=6.6
        - cloudpickle >=0.2.2
        - cytoolz >=0.7.4
        - dask-core >=0.18.0
        - msgpack-python
        - psutil >=5.0
        - python >=3.7,<3.8.0a0
        - pyyaml
        - six
        - sortedcontainers !=2.0.0,!=2.0.1
        - tblib
        - toolz >=0.7.4
        - tornado >=5
        - zict >=0.1.3
test:
    commands:
        - dask-scheduler --help
        - dask-ssh --help
        - dask-worker --help
    imports:
        - distributed
        - distributed.cli
        - distributed.comm
        - distributed.deploy
        - distributed.diagnostics
        - distributed.protocol
about:
    description: 'Distributed is a lightweight library for distributed computing in
        Python.

        It extends both the concurrent.futures and dask APIs to moderate sized

        clusters.

        '
    dev_url: https://github.com/dask/distributed
    doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
    doc_url: http://distributed.readthedocs.org
    home: http://distributed.readthedocs.io/en/latest/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Distributed computing with Dask
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - marcelotrevisani
        - martindurant
        - mrocklin
        - ogrisel
        - pitrou
        - tomaugspurger
