# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# C:\ci\containers\000038hkc66\tmp\build\80754af9\rsync-recipes\multipledispatch-0.6.0-python_3.7-on-winbuilder, last modified Tue Aug 14 12:43:29 2018
# ------------------------------------------------

package:
    name: multipledispatch
    version: 0.6.0
source:
    fn: multipledispatch-0.6.0.tar.gz
    sha256: a7ab1451fd0bf9b92cab3edbd7b205622fb767aeefb4fb536c2e3de9e0a38bea
    url: https://pypi.io/packages/source/m/multipledispatch/multipledispatch-0.6.0.tar.gz
build:
    number: '0'
    script: C:\ci\multipledispatch_1534269095440\_h_env\python.exe -m pip install
        . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - certifi 2018.8.13 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.0.0 py37_0
        - six 1.11.0 py37_1
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - multipledispatch
about:
    description: 'This implementation of multiple dispatch is efficient, mostly complete,

        performs static analysis to avoid conflicts, and provides optional

        namespace support.

        '
    dev_url: https://github.com/mrocklin/multipledispatch/
    doc_source_url: https://github.com/mrocklin/multipledispatch/blob/master/docs/source/index.rst
    doc_url: https://multiple-dispatch.readthedocs.io
    home: https://github.com/mrocklin/multipledispatch/
    license: BSD 3-Clause
    license_family: BSD
    summary: Multiple dispatch in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
