# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# C:\ci\containers\000015dh1in\tmp\build\80754af9\rsync-recipes\future-0.17.1-python_3.7-on-winbuilder, last modified Thu Nov  1 23:44:52 2018
# ------------------------------------------------

package:
    name: future
    version: 0.17.1
source:
    fn: future-0.17.1.tar.gz
    sha256: 67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8
    url: https://pypi.io/packages/source/f/future/future-0.17.1.tar.gz
build:
    entry_points:
        - futurize = libfuturize.main:main
        - pasteurize = libpasteurize.main:main
    number: '0'
    script: C:\\ci\\future_1541134251214\\_h_env\\python.exe setup.py install --single-version-externally-managed
        --record record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.10.15 py37_0
        - python 3.7.1 h33f27b4_4
        - setuptools 40.5.0 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - futurize -h
        - pasteurize -h
    imports:
        - future
about:
    description: 'Python-future  is the missing compatibility layer between Python
        2 and

        Python 3. It allows you to use a single, clean Python 3.x-compatible

        codebase to support both Python 2 and Python 3 with minimal overhead.

        '
    dev_url: https://github.com/PythonCharmers/python-future
    doc_url: http://python-future.org
    home: http://python-future.org
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: Clean single-source support for Python 3 and 2
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mmysinger
