# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# C:\ci\containers\00000omedar\tmp\build\80754af9\rsync-recipes\comtypes-1.1.7-python_3.7-on-winbuilder, last modified Wed Aug  8 14:01:08 2018
# ------------------------------------------------

package:
    name: comtypes
    version: 1.1.7
source:
    fn: comtypes-1.1.7.tar.gz
    sha256: 77ba1f0bd59f669dfb26e45702042e0a41bd6aa924257c4d00f74cc11b0a6087
    url: https://github.com/enthought/comtypes/archive/1.1.7.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.0.0 py37_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - comtypes
about:
    description: 'comtypes is a pure Python COM package based on the ctypes ffi foreign

        function library.The comtypes package makes it easy to access and implement

        both custom and dispatch based COM interfaces.While the pywin32 package

        contains superior client side support for dispatch based COM interfaces,it
        is

        not possible to access custom COM interfaces unless they are wrapped in

        C++-code.

        '
    dev_url: https://github.com/enthought/comtypes/
    doc_source_url: https://github.com/enthought/comtypes/blob/master/docs/source/index.rst
    doc_url: http://pythonhosted.org/comtypes/
    home: http://starship.python.net/crew/theller/comtypes/
    license: MIT
    license_file: LICENSE.txt
    summary: pure Python COM package
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
