# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003270m3n\tmp\build\80754af9\rsync-recipes\more-itertools-6.0.0-python_3.7-on-winbuilder, last modified Mon Mar 11 21:28:56 2019
# ------------------------------------------------

package:
    name: more-itertools
    version: 6.0.0
source:
    sha256: 590044e3942351a1bdb1de960b739ff4ce277960f2425ad4509446dbace8d9d1
    url: https://pypi.org/packages/source/m/more-itertools/more-itertools-6.0.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - more_itertools
        - more_itertools.tests
about:
    description: 'more-itertools, additional building blocks, recipes, and routines
        for

        working with Python iterables.

        '
    dev_url: https://github.com/erikrose/more-itertools
    doc_url: https://more-itertools.readthedocs.io/en/latest/api.html
    home: https://github.com/erikrose/more-itertools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: More routines for operating on iterables, beyond itertools
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
