# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# C:\ci\containers\00000nsu9qc\tmp\build\80754af9\rsync-recipes\pytest-arraydiff-0.3-python_3.7-on-winbuilder, last modified Wed Dec 19 09:01:14 2018
# ------------------------------------------------

package:
    name: pytest-arraydiff
    version: '0.3'
source:
    fn: pytest-arraydiff-0.3.tar.gz
    sha256: de2d62f53ecc107ed754d70d562adfa7573677a263216a7f19aa332f20dc6c15
    url: https://pypi.io/packages/source/p/pytest-arraydiff/pytest-arraydiff-0.3.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37h39e3cac_0
requirements:
    host:
        - atomicwrites 1.2.1 py37_0
        - attrs 18.2.0 py37h28b3542_0
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - colorama 0.4.1 py37_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - mkl 2019.1 144
        - more-itertools 4.3.0 py37_0
        - numpy 1.11.3 py37h35d8231_12
        - numpy-base 1.11.3 py37hc3f5095_12
        - openssl 1.1.1a he774522_0
        - pip 18.1 py37_0
        - pluggy 0.8.0 py37_0
        - py 1.7.0 py37_0
        - pytest 4.0.2 py37_0
        - python 3.7.1 h8c8aaf0_6
        - setuptools 40.6.3 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - numpy
        - pytest
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - pytest_arraydiff
about:
    description: 'This is a py.test plugin to facilitate the generation and comparison
        of

        data arrays produced during tests.

        '
    dev_url: https://github.com/astrofrog/pytest-arraydiff
    doc_url: https://github.com/astrofrog/pytest-arraydiff
    home: https://github.com/astrofrog/pytest-arraydiff
    license: BSD
    summary: pytest plugin to help with comparing array output from tests
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - drdavella
        - mwcraig
