# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003ngfio8\tmp\build\80754af9\rsync-recipes\python-dateutil-2.8.0-python_3.7-on-winbuilder, last modified Mon Feb 25 15:13:47 2019
# ------------------------------------------------

package:
    name: python-dateutil
    version: 2.8.0
source:
    sha256: c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e
    url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.8.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - setuptools_scm 3.2.0 py_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - six >=1.5
test:
    imports:
        - dateutil
        - dateutil.parser
        - dateutil.rrule
        - dateutil.tz
        - dateutil.zoneinfo
about:
    description: 'The dateutil module provides powerful extensions to the standard
        datetime

        module, available in Python.

        '
    dev_url: https://github.com/dateutil/dateutil/
    doc_source_url: https://github.com/dateutil/dateutil/blob/master/docs/index.rst
    doc_url: https://dateutil.readthedocs.org/en/latest/
    home: https://dateutil.readthedocs.org/
    license: BSD 3 Clause
    license_file: LICENSE
    summary: Extensions to the standard Python datetime module.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pganssle
