# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000001qofbs\tmp\build\80754af9\rsync-recipes\markupsafe-1.1.1-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Mon Feb 25 17:13:53 2019
# ------------------------------------------------

package:
    name: markupsafe
    version: 1.1.1
source:
    sha256: 29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b
    url: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-1.1.1.tar.gz
build:
    number: '0'
    script: C:\ci\markupsafe_1551192402207\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - markupsafe
about:
    description: 'MarkupSafe is a library for Python that implements a unicode string
        that

        is aware of HTML escaping rules and can be used to implement automatic

        string escaping. It is used by Jinja 2, the Mako templating engine, the

        Pylons web framework and many more.

        '
    dev_url: https://github.com/pallets/markupsafe
    doc_source_url: https://github.com/pallets/markupsafe/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/MarkupSafe
    home: https://www.palletsprojects.com/p/markupsafe
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.rst
    summary: A Python module that implements the jinja2.Markup string
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - scopatz
