# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# C:\ci\containers\00002mso5qu\tmp\build\80754af9\rsync-recipes\libiconv-1.15-c_compilervs2015-on-winbuilder, last modified Mon Nov 13 11:50:02 2017
# ------------------------------------------------

package:
    name: libiconv
    version: '1.15'
source:
    fn: libiconv-1.15.tar.gz
    patches:
        - CMakeLists.txt.patch
        - config.h.patch
        - configure.cmake.patch
    sha256: ccf536620a45458d26ba83887a983b96827001e92a13847b45e4925cc8913178
    url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz
build:
    number: '7'
    run_exports:
        - libiconv >=1.15,<2.0a0
    string: h1df5818_7
requirements:
    build:
        - cmake 3.9.4 h4b83b1b_0
        - vc 14 h2379b0c_2
        - vs2015_runtime 14.0.25123 hd4c4e62_2
        - vs2015_win-64 14.0.25123 hf5d5b87_2
    run:
        - vc 14.*
about:
    description: 'This library provides an iconv() implementation, for use on systems
        which don''t have one,

        or whose implementation cannot convert from/to Unicode.

        '
    dev_url: http://git.savannah.gnu.org/cgit/libiconv.git/tree/
    doc_url: https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.15/iconv.1.html
    home: https://www.gnu.org/software/libiconv/
    license: GPL and LGPL
    summary: Provides iconv for systems which don't have one (or that cannot convert
        from/to Unicode.)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jhamman
        - ocefpaf
