# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\fastcache-feedstock\recipe, last modified Tue Jul  3 15:47:17 2018
# ------------------------------------------------

package:
    name: fastcache
    version: 1.0.2
source:
    fn: fastcache-1.0.2.tar.gz
    sha256: 867005774917f999854ffd303fbe3793c30c2dc9279b78ec315dd4e57e4284e6
    url: https://pypi.io/packages/source/f/fastcache/fastcache-1.0.2.tar.gz
build:
    number: '2'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37hfa6e2cd_2
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc 14.*
test:
    commands:
        - python -c "import fastcache; fastcache.test()"
    imports:
        - fastcache
        - fastcache._lrucache
    requires:
        - pytest
about:
    description: 'fastcache provides speedup of 10-30x over standard library.

        It passes test suite from standard library for lru_cache.

        '
    dev_url: https://github.com/pbrady/fastcache
    doc_source_url: https://github.com/pbrady/fastcache/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/fastcache/1.0.2
    home: https://github.com/pbrady/fastcache
    license: MIT
    license_family: MIT
    license_file: C:\Users\builder\conda\aggregate\fastcache-feedstock\recipe/LICENSE
    summary: C implementation of Python 3 lru_cache
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - synapticarbors
