# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003cheg62\tmp\build\80754af9\rsync-recipes\qtawesome-0.5.7-python_3.7-on-winbuilder, last modified Fri Mar 22 15:49:04 2019
# ------------------------------------------------

package:
    name: qtawesome
    version: 0.5.7
source:
    sha256: 510972e327a6013f962b41cc14d27cff2689fbd8d38bb0816bc4b890d699e0b0
    url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-0.5.7.tar.gz
build:
    noarch: false
    number: '1'
    script: C:\ci\qtawesome_1553292025562\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - qtpy
        - six
test:
    imports:
        - qtawesome
    requires:
        - pyqt
about:
    home: https://github.com/spyder-ide/qtawesome
    license: MIT
    license_file: LICENSE
    summary: Iconic fonts in PyQt and PySide applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - ccordoba12
        - goanpeca
