# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\bottleneck-feedstock\recipe, last modified Tue Jul  3 15:45:50 2018
# ------------------------------------------------

package:
    name: bottleneck
    version: 1.2.1
source:
    fn: Bottleneck-1.2.1.tar.gz
    sha256: 6efcde5f830aed64feafca0359b51db0e184c72af8ba6675b4a99f263922eb36
    url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-1.2.1.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37h452e1ab_1
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - blas 1.0 mkl
        - certifi 2018.4.16 py37_0
        - icc_rt 2017.0.4 h97af966_0
        - intel-openmp 2018.0.3 0
        - mkl 2018.0.3 1
        - numpy 1.11.3 py37hd5b3723_8
        - numpy-base 1.11.3 py37h5c71026_8
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wincertstore 0.2 py37_0
    run:
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc 14.*
test:
    commands:
        - python -c "import bottleneck; bottleneck.test()"
    imports:
        - bottleneck
        - bottleneck.move
        - bottleneck.nonreduce
        - bottleneck.nonreduce_axis
        - bottleneck.reduce
        - bottleneck.slow
        - bottleneck.tests
    requires:
        - nose
about:
    description: 'Bottleneck is a collection of fast NumPy array functions written
        in

        Cython.

        '
    dev_url: https://github.com/kwgoodman/bottleneck
    doc_url: http://berkeleyanalytics.com/bottleneck
    home: http://berkeleyanalytics.com/bottleneck
    license: BSD 2-Clause
    license_family: BSD
    license_file: bottleneck/LICENSE
    summary: Fast NumPy array functions written in Cython.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - wesm
