# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# C:\ci\containers\000018p57b1\tmp\build\80754af9\rsync-recipes\pycurl-7.43.0.2-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Tue Dec 18 13:47:30 2018
# ------------------------------------------------

package:
    name: pycurl
    version: 7.43.0.2
source:
    patches:
        - msvc_warnings.patch
    sha256: 0f0cdfc7a92d4f2a5c44226162434e34f7d6967d3af416a6f1448649c09a25a4
    url: https://pypi.io/packages/source/p/pycurl/pycurl-7.43.0.2.tar.gz
build:
    detect_binary_files_with_prefix: false
    number: '0'
    string: py37h7a1dbc1_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2018.03.07 0
        - krb5 1.16.1 hc04afaa_7
        - libcurl 7.63.0 h2a8f88b_1000
        - libssh2 1.8.0 h7a1dbc1_4
        - openssl 1.1.1a he774522_0
        - python 3.7.1 h8c8aaf0_6
        - sqlite 3.26.0 he774522_0
        - tk 8.6.8 hfa6e2cd_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - libcurl >=7.63.0,<8.0a0
        - openssl >=1.1.1a,<1.1.2a
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - curl
        - pycurl
about:
    description: 'PycURL is a Python interface to libcurl, the multiprotocol file
        transfer library.

        Similarly to the urllib Python module, PycURL can be used to fetch objects
        identified

        by a URL from a Python program.

        '
    dev_url: https://github.com/pycurl/pycurl
    doc_source_url: https://github.com/pycurl/pycurl/blob/master/doc/index.rst
    doc_url: http://pycurl.io/docs/latest/index.html
    home: http://pycurl.sourceforge.net/
    license: LGPL, MIT
    license_family: LGPL
    summary: A Python Interface To The cURL library
extra:
    copy_test_source_files: true
    final: true
