# This file created by conda-build 3.17.4
# ------------------------------------------------

package:
    name: mkl_random
    version: 1.0.2
source:
    -   patches:
            - 0001-fix-windows-case-sensitivity.patch
            - 0002-simplify-arch-flags.patch
            - 0003-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
            - 0004-disable-memmap-filename-test-due-to-CI-link-confusio.patch
            - 0005-disable-broken-tests.patch
            - 0006-use-mklfft-when-available.patch
            - 0007-define-mkl_version-in-__init__.py.patch
            - 0008-intel-umath-optimizations.patch
            - 0009-intel-mkl_mem-all.patch
            - 0010-intel-init_mkl.patch
            - 0011-intel-mkl_random.patch
            - 0012-Remove-ICC-specific-flags.patch
            - 0013-Remove-np.invsqrt.patch
            - 0014-Rewrite-inlining.patch
        sha256: 3d734559db35aa3697dadcea492a423118c5c55d176da2f3be9c98d4803fc2a7
        url: https://pypi.io/packages/source/n/numpy/numpy-1.15.4.zip
    -   folder: mkl_random
        sha256: 2270ef2834f6552850533aad01500d27c8e056f2cfbdbdb751593000aea1159e
        url: https://github.com/IntelPython/mkl_random/archive/v1.0.2.tar.gz
    -   folder: mkl_fft
        sha256: 3c7ed29e203c5b664ecafb11d767d62f9cae4aa56f9a95737e121192a66673bf
        url: https://github.com/IntelPython/mkl_fft/archive/v1.0.6.tar.gz
build:
    number: 0
    string: py37h343c172_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 hb4ce483_1
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - cython 0.29 py37ha925a31_0
        - intel-openmp 2019.0 117
        - mkl 2019.1 144
        - mkl-devel 2019.1 145
        - mkl-include 2019.1 144
        - numpy-base 1.11.*
        - openssl 1.1.1a he774522_0
        - python 3.7.1 he44a216_5
        - setuptools 40.6.2 py37_0
        - vc 14.1 h21ff451_4
        - vs2015_runtime 14.15.26706 h3a45250_1
        - wincertstore 0.2 py37_0
    run:
        - blas 1.0 mkl
        - mkl >=2019.1,<2020.0a0
        - numpy-base >=1.0.2,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    commands:
        - nosetests -v mkl_random
    imports:
        - mkl_random
        - mkl_random.mklrand
    requires:
        - nose
        - numpy-base >=1.13
about:
    description: NumPy-based implementation of random number generation sampling using
        Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices
        of sampling algorithms available in MKL.
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: mkl_random/LICENSE.txt
    summary: Intel (R) MKL-powered package for sampling from common probability distributions
        into NumPy arrays.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
