# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000001qofbf\tmp\build\80754af9\rsync-recipes\wheel-0.33.1-python_3.7-on-winbuilder, last modified Mon Feb 25 17:13:45 2019
# ------------------------------------------------

package:
    name: wheel
    version: 0.33.1
source:
    sha256: 66a8fd76f28977bb664b098372daef2b27f60dc4d1688cfab7b37a09448f0e9d
    url: https://pypi.io/packages/source/w/wheel/wheel-0.33.1.tar.gz
build:
    entry_points:
        - wheel = wheel.cli:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - wheel --help
    imports:
        - wheel
about:
    home: https://github.com/pypa/wheel
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
