# This file created by conda-build 3.17.7
# meta.yaml template originally from:
# C:\ci\containers\00001iiossq\tmp\build\80754af9\rsync-recipes\libxml2-2.9.9-c_compiler_vs2017-on-winbuilder, last modified Sat Jan 19 09:09:43 2019
# ------------------------------------------------

package:
    name: libxml2
    version: 2.9.9
source:
    patches:
        - 0004-CVE-2017-8872.patch
    sha256: 94fb70890143e3c6549f265cee93ec064c80a84c42ad0f23e85ee1fd6540a871
    url: http://xmlsoft.org/sources/libxml2-2.9.9.tar.gz
build:
    number: '0'
    run_exports:
        - libxml2 >=2.9.9,<2.10.0a0
    string: h464c3ec_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - libiconv 1.15 h1df5818_7
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - libiconv >=1.15,<2.0a0
        - vc >=14.1,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - xmllint test.xml
    files:
        - test.xml
about:
    description: 'Though libxml2 is written in C a variety of language

        bindings make it available in other environments.

        '
    dev_url: https://git.gnome.org/browse/libxml2/
    doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
    doc_url: http://xmlsoft.org/html/index.html
    home: http://xmlsoft.org/
    license: MIT
    license_family: MIT
    license_file: Copyright
    summary: The XML C parser and toolkit of Gnome
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - jakirkham
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
