# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\cycler-feedstock\recipe, last modified Tue Jul  3 15:46:35 2018
# ------------------------------------------------

package:
    name: cycler
    version: 0.10.0
source:
    fn: cycler-v0.10.0.tar.gz
    sha256: b6d217635e03024196225367b1a438996dbbf0271bec488f00584f0e7dc15cfa
    url: https://github.com/matplotlib/cycler/archive/v0.10.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - six 1.11.0 py37_1
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - cycler
about:
    description: 'Cycler is a package used to create composable style cycles.

        '
    dev_url: https://github.com/matplotlib/cycler
    doc_source_url: https://github.com/matplotlib/cycler/blob/master/doc/source/index.rst
    doc_url: http://matplotlib.org/cycler/
    home: http://matplotlib.org/cycler
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Composable style cycles.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - janschulz
        - ocefpaf
        - pelson
        - tacaswell
