# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003cheg4c\tmp\build\80754af9\rsync-recipes\menuinst-1.4.16-python_3.7-c_compiler_vs2017-on-winbuilder, last modified Thu Mar 14 02:34:56 2019
# ------------------------------------------------

package:
    name: menuinst
    version: 1.4.16
source:
    git_rev: 1.4.16
    git_url: https://github.com/ContinuumIO/menuinst.git
build:
    entry_points:
        - menuinst = menuinst.main:main
    skip_compile_pyc:
        - cwp.py
    string: py37he774522_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - pywin32
        - vc >=14.1,<15.0a0
test:
    commands:
        - menuinst -h
        - menuinst --version
    imports:
        - menuinst
        - menuinst.winshortcut
about:
    description: 'This application is used by Conda to create shortcuts on a wide
        variety of

        systems.

        '
    dev_url: https://github.com/ContinuumIO/menuinst
    doc_source_url: https://github.com/ContinuumIO/menuinst
    doc_url: https://pypi.python.org/pypi/menuinst/
    home: https://github.com/ContinuumIO/menuinst
    license: BSD
    summary: cross platform menu item installation
extra:
    copy_test_source_files: true
    final: true
