# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\bkcharts-feedstock\recipe, last modified Tue Jul  3 15:45:40 2018
# ------------------------------------------------

package:
    name: bkcharts
    version: '0.2'
source:
    fn: bkcharts-0.2.tar.gz
    sha256: a5eaa8e78853dcecaa46345812e4fabe9cd3b96330ebf0809f640a4a0556d72e
    url: https://pypi.io/packages/source/b/bkcharts/bkcharts-0.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - numpy >=1.7.1
        - pandas
        - python >=3.7,<3.8.0a0
        - six >=1.5.2
about:
    dev_url: http://github.com/bokeh/bkcharts
    home: http://github.com/bokeh/bkcharts
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: High level chart types built on top of Bokeh
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
