# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002g6vmsc\tmp\build\80754af9\rsync-recipes\pytables-3.5.1-cxx_compiler_vs2017-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Mon Mar 18 12:13:16 2019
# ------------------------------------------------

package:
    name: pytables
    version: 3.5.1
source:
    sha256: 88e2f3be1f143febc8bf8a7fe49ad51fc12518d6a1ac4eb641778d93e5dc2039
    url: https://pypi.io/packages/source/t/tables/tables-3.5.1.tar.gz
build:
    entry_points:
        - pt2to3 = tables.scripts.pt2to3:main
        - ptdump = tables.scripts.ptdump:main
        - ptrepack = tables.scripts.ptrepack:main
        - pttree = tables.scripts.pttree:main
    number: '0'
    string: py37h1da0976_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - blas 1.0 mkl
        - blosc 1.15.0 h7bd577a_0
        - bzip2 1.0.6 hfa6e2cd_5
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - cython 0.29.6 py37ha925a31_0
        - hdf5 1.10.4 h7ebc959_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - lzo 2.10 h6df0209_2
        - mkl 2018.0.3 1
        - numexpr 2.6.8 py37h9ef55f4_0
        - numpy 1.11.3 py37h53ece5f_11
        - numpy-base 1.11.3 py37h8128ebf_11
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - snappy 1.1.7 h777316e_3
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - blosc >=1.15.0,<2.0a0
        - bzip2 >=1.0.6,<2.0a0
        - hdf5 >=1.10.4,<1.10.5.0a0
        - lzo >=2.10,<3.0a0
        - numexpr
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - six
        - vc >=14.1,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pt2to3 -h
        - ptdump -h
        - ptrepack -h
        - pttree -h
    requires:
        - mock
        - setuptools
about:
    description: 'PyTables is a package for managing hierarchical datasets and designed
        to

        efficiently and easily cope with extremely large amounts of data. PyTables

        is built on top of the HDF5 library, using the Python language and the

        NumPy package.

        '
    dev_url: https://github.com/PyTables
    doc_url: http://www.pytables.org/
    home: http://www.pytables.org
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Brings together Python, HDF5 and NumPy to easily handle large amounts
        of data.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - scopatz
        - tomkooij
