# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# C:\ci\containers\00001ehk9ki\tmp\build\80754af9\rsync-recipes\pytest-astropy-0.5.0-python_3.7-on-winbuilder, last modified Tue Dec 18 02:22:18 2018
# ------------------------------------------------

package:
    name: pytest-astropy
    version: 0.5.0
source:
    fn: pytest-astropy-0.5.0.tar.gz
    sha256: 6f28fb81dcdfa745f423b8f6d0303d97357d775b4128bcc2b3668f1602fd5a0b
    url: https://pypi.io/packages/source/p/pytest-astropy/pytest-astropy-0.5.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 18.1 py37_0
        - python 3.7.1 h8c8aaf0_6
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - pytest >=3.1
        - pytest-arraydiff >=0.1
        - pytest-doctestplus >=0.2.0
        - pytest-openfiles >=0.3.1
        - pytest-remotedata >=0.3.1
        - python >=3.7,<3.8.0a0
test:
    imports:
        - pytest_arraydiff
        - pytest_doctestplus
        - pytest_openfiles
        - pytest_remotedata
about:
    description: 'This is a meta-package that pulls in the dependencies that are used
        by

        astropy and some affiliated packages for testing. It can also be used for

        testing packages that are not affiliated with the Astropy project.

        '
    dev_url: https://github.com/astropy/pytest-astropy
    doc_url: https://github.com/astropy/pytest-astropy
    home: https://github.com/astropy/pytest-astropy
    license: BSD
    summary: Meta-package containing dependencies for testing Astropy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - drdavella
        - mwcraig
