# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\00003f294me\tmp\build\80754af9\rsync-recipes\alabaster-0.7.12-python_3.7-on-winbuilder, last modified Mon Oct  8 13:30:01 2018
# ------------------------------------------------

package:
    name: alabaster
    version: 0.7.12
source:
    sha256: a661d72d58e6ea8a57f7a86e37d86716863ee5e92788398526d58b26a4e4dc02
    url: https://pypi.io/packages/source/a/alabaster/alabaster-0.7.12.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.4.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.0 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - python -c "import alabaster; print(alabaster.get_path())"
    imports:
        - alabaster
about:
    description: 'Alabaster is a visually clean, responsive, and configurable Sphinx

        theme. It is sidebar-enabled and easy to install/use as a Python

        package. As of Sphinx 1.3, Alabaster is selected as the default

        theme for Sphinx.

        '
    dev_url: https://github.com/bitprophet/alabaster
    doc_url: https://anaconda.org/anaconda/alabaster
    home: http://www.sphinx-doc.org/en/stable/index.html
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Configurable, Python 2+3 compatible Sphinx theme.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - r-jain1
