# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\tblib-feedstock\recipe, last modified Tue Jul  3 15:55:42 2018
# ------------------------------------------------

package:
    name: tblib
    version: 1.3.2
source:
    fn: tblib-1.3.2.tar.gz
    sha256: 436e4200e63d92316551179dc540906652878df4ff39b43db30fcf6400444fe7
    url: https://pypi.io/packages/source/t/tblib/tblib-1.3.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - tblib
about:
    description: 'tblib allows you to Pickle tracebacks and raise exceptions with
        pickled

        tracebacks in different processes.This allows better error handling when

        running code over multiple processes.

        '
    dev_url: https://github.com/ionelmc/python-tblib
    doc_source_url: https://github.com/ionelmc/python-tblib/blob/master/docs/index.rst
    doc_url: https://python-tblib.readthedocs.io/en/latest/
    home: https://github.com/ionelmc/python-tblib
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Traceback serialization library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
