# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000029cv5k6\tmp\build\80754af9\rsync-recipes\decorator-4.4.0-python_3.7-on-winbuilder, last modified Fri Mar 22 13:29:18 2019
# ------------------------------------------------

package:
    name: decorator
    version: 4.4.0
source:
    sha256: 86156361c50488b84a3f148056ea716ca587df2f0de1d34750d35c21312725de
    url: https://pypi.io/packages/source/d/decorator/decorator-4.4.0.tar.gz
build:
    noarch: false
    number: '1'
    script: C:\ci\decorator_1553290042897\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - decorator
about:
    description: 'Preserve the signature of decorated functions in a consistent way

        across Python releases.

        '
    dev_url: https://github.com/micheles/decorator
    doc_source_url: https://github.com/micheles/decorator/tree/master/docs
    doc_url: http://decorator.readthedocs.io/en/stable/
    home: https://github.com/micheles/decorator
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Better living through Python with decorators.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
