# This file created by conda-build 3.16.1
# meta.yaml template originally from:
# C:\ci\containers\00002lbdmgb\tmp\build\80754af9\rsync-recipes\libssh2-1.8.0-c_compiler_vs2017-on-winbuilder, last modified Thu Oct 25 14:05:35 2018
# ------------------------------------------------

package:
    name: libssh2
    version: 1.8.0
source:
    fn: libssh2-1.8.0.tar.gz
    sha256: 39f34e2f6835f4b992cafe8625073a88e5a28ba78f83e8099610a7b3af4676d4
    url: https://www.libssh2.org/download/libssh2-1.8.0.tar.gz
build:
    number: '4'
    run_exports:
        - libssh2 >=1.8.0,<2.0a0
    string: h7a1dbc1_4
requirements:
    build:
        - cmake-binary 3.9.1 h8f04fe6_1
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2018.03.07 0
        - openssl 1.1.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - openssl >=1.1.1,<1.1.2.0a0
        - vc >=14.1,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_INC%\\libssh2.h           exit 1
        - if not exist %LIBRARY_INC%\\libssh2_publickey.h exit 1
        - if not exist %LIBRARY_INC%\\libssh2_sftp.h      exit 1
        - if not exist %LIBRARY_LIB%\\libssh2.lib         exit 1
about:
    description: 'libssh2 is a library implementing the SSH2 protocol, available under
        the revised BSD license.

        '
    dev_url: https://github.com/libssh2/libssh2
    home: https://www.libssh2.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: the SSH library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - shadowwalkersb
