# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\babel-feedstock\recipe, last modified Tue Jul  3 15:45:25 2018
# ------------------------------------------------

package:
    name: babel
    version: 2.6.0
source:
    fn: Babel-2.6.0.tar.gz
    sha256: 8cba50f48c529ca3fa18cf81fa9403be176d374ac4d60738b839122dfaaa3d23
    url: https://pypi.io/packages/source/B/Babel/Babel-2.6.0.tar.gz
build:
    entry_points:
        - pybabel = babel.messages.frontend:main
    number: '0'
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - pytz 2018.5 py37_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - pytz
test:
    commands:
        - pybabel --help
    imports:
        - babel
        - babel.localtime
        - babel.messages
about:
    description: 'Babel is an integrated collection of utilities that assist in

        internationalizing and localizing Python applications, with an emphasis

        on web-base applications.

        '
    dev_url: https://github.com/python-babel/babel
    doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
    doc_url: http://babel.pocoo.org/en/latest/#user-documentation
    home: http://babel.pocoo.org/
    license: BSD 3-clause
    license_file: LICENSE
    summary: Utilities to internationalize and localize Python applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - frol
        - nehaljwani
