# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003ngfio5\tmp\build\80754af9\rsync-recipes\pyodbc-4.0.26-cxx_compiler_vs2017-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Mon Feb 25 15:14:34 2019
# ------------------------------------------------

package:
    name: pyodbc
    version: 4.0.26
source:
    fn: pyodbc-4.0.26.tar.gz
    sha256: e52700b5d24a846483b5ab80acd9153f8e593999c9184ffea11596288fb33de3
    url: https://pypi.io/packages/source/p/pyodbc/pyodbc-4.0.26.tar.gz
build:
    number: '0'
    script: C:\ci\pyodbc_1551146976652\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37ha925a31_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - pyodbc
about:
    description: 'pyodbc is a Python DB API 2 module for ODBC. This project provides
        an

        up-to-date, convenient interface to ODBC using native data types like

        datetime and decimal.

        '
    dev_url: https://github.com/mkleehammer/pyodbc
    doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
    doc_url: http://mkleehammer.github.io/pyodbc/
    home: https://github.com/mkleehammer/pyodbc
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: DB API Module for ODBC
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
