# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\00001hdkbcl\tmp\build\80754af9\rsync-recipes\krb5-1.16.1-cxx_compiler_vs2017-vc_14-c_compiler_vs2017-on-winbuilder, last modified Fri Oct 26 16:33:59 2018
# ------------------------------------------------

package:
    name: krb5
    version: 1.16.1
source:
    patches:
        - escape_curly_braces.patch
    sha256: d46a676bd6cfe58b8684ffd881bc7ed2c9c90cb43ccfa45a9500530e84aa262b
    url: https://github.com/krb5/krb5/archive/krb5-1.16.1-final.tar.gz
build:
    number: '7'
    run_exports:
        - krb5 >=1.16.1,<1.17.0a0
    string: hc04afaa_7
requirements:
    build:
        - m2-base 1.0.0 2
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-dash 0.5.8 2
        - m2-diffutils 3.3 4
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gettext 0.19.7 4
        - m2-gmp 6.1.0 3
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libbz2 1.0.6 3
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-liblzma 5.2.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-make 4.1 5
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-sed 4.2.2 3
        - m2-tar 1.28 4
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-unzip 6.0 3
        - m2-util-linux 2.26.2 2
        - m2-which 2.21 3
        - m2-zip 3.0 2
        - m2-zlib 1.2.8 4
        - msys2-conda-epoch 20160418 1
        - perl 5.26.2.1 h0c8e037_0
        - posix 1.0.0 2
        - python 2.7.15 h2880e7c_2
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2018.03.07 0
        - openssl 1.1.1 he774522_0
        - tk 8.6.8 hfa6e2cd_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - openssl >=1.1.1,<1.1.2.0a0
        - tk >=8.6.8,<8.7.0a0
        - vc >=14.1,<15.0a0
about:
    home: http://web.mit.edu/kerberos/
    license: MIT
    license_file: doc/notice.rst
    summary: A network authentication protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - ocefpaf
        - pelson
