# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# C:\ci\containers\00000fiukuj\tmp\build\80754af9\rsync-recipes\pytest-remotedata-0.3.1-python_3.7-on-winbuilder, last modified Wed Oct 31 22:05:33 2018
# ------------------------------------------------

package:
    name: pytest-remotedata
    version: 0.3.1
source:
    fn: pytest-remotedata-0.3.1.tar.gz
    sha256: 15b75a38431da96a4da5e48b20a18e4dcc40d191abc199b17cb969f818530481
    url: https://pypi.io/packages/source/p/pytest-remotedata/pytest-remotedata-0.3.1.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - certifi 2018.10.15 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.1 h33f27b4_4
        - setuptools 40.4.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.2 py37_0
        - wincertstore 0.2 py37_0
    run:
        - pytest >=3.1
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - pytest_remotedata
about:
    description: 'This package provides a plugin for the pytest framework that allows

        developers to control unit tests that require access to data from the

        internet.

        '
    dev_url: https://github.com/astropy/pytest-remotedata
    doc_url: https://github.com/astropy/pytest-remotedata
    home: https://github.com/astropy/pytest-remotedata
    license: BSD
    summary: Pytest plugin for controlling remote data access
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - drdavella
        - mwcraig
