# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\pandocfilters-feedstock\recipe, last modified Tue Jul  3 15:51:46 2018
# ------------------------------------------------

package:
    name: pandocfilters
    version: 1.4.2
source:
    fn: pandocfilters-1.4.2.tar.gz
    sha256: b3dd70e169bb5449e6bc6ff96aea89c5eea8c5f6ab5e207fc2f521a2cf4a0da9
    url: https://pypi.io/packages/source/p/pandocfilters/pandocfilters-1.4.2.tar.gz
build:
    number: '1'
    script: pip install --no-deps .
    string: py37_1
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - pandocfilters
about:
    dev_url: https://github.com/jgm/pandocfilters
    home: https://github.com/jgm/pandocfilters
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A python module for writing pandoc filters
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
