# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003ngfip5\tmp\build\80754af9\rsync-recipes\xlsxwriter-1.1.5-python_3.7-on-winbuilder, last modified Mon Feb 25 15:14:32 2019
# ------------------------------------------------

package:
    name: xlsxwriter
    version: 1.1.5
source:
    fn: XlsxWriter-1.1.5.tar.gz
    sha256: de9ef46088489915eaaee00c7088cff93cf613e9990b46b933c98eb46f21b47f
    url: https://pypi.io/packages/source/X/XlsxWriter/XlsxWriter-1.1.5.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - xlsxwriter
about:
    description: 'XlsxWriter is a Python module that can be used to write text, numbers,
        formulas

        and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.

        '
    dev_url: https://github.com/jmcnamara/XlsxWriter
    doc_source_url: https://github.com/jmcnamara/XlsxWriter/blob/master/docs/XlsxWriter.pdf
    doc_url: https://xlsxwriter.readthedocs.org/
    home: https://xlsxwriter.readthedocs.io/
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: A Python module for creating Excel XLSX files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mcs07
        - nehaljwani
