# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003cheg4h\tmp\build\80754af9\rsync-recipes\pytest-4.3.1-python_3.7-on-winbuilder, last modified Mon Mar 18 10:52:30 2019
# ------------------------------------------------

package:
    name: pytest
    version: 4.3.1
source:
    sha256: 592eaa2c33fae68c7d75aacf042efc9f77b27c08a6224a4f59beab8d9a420523
    url: https://pypi.io/packages/source/p/pytest/pytest-4.3.1.tar.gz
build:
    entry_points:
        - py.test = py.test:main
        - pytest = py.test:main
    number: '0'
    script: C:\ci\pytest_1552927016155\_h_env\python.exe setup.py install --single-version-externally-managed
        --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - setuptools_scm 3.2.0 py_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - atomicwrites >=1.0
        - attrs >=17.4.0
        - colorama
        - more-itertools >=4.0
        - pluggy >=0.7
        - py >=1.5.0
        - python >=3.7,<3.8.0a0
        - setuptools >=40.0
        - six >=1.10.0
test:
    commands:
        - pytest -h
    imports:
        - pytest
about:
    description: 'The pytest framework makes it easy to write small tests, yet scales
        to

        support complex functional testing for applications and libraries.

        '
    dev_url: https://github.com/pytest-dev/pytest/
    doc_url: https://docs.pytest.org/en/latest/
    home: https://docs.pytest.org/en/latest/
    license: MIT
    license_file: LICENSE
    summary: Simple and powerful testing with Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - flub
        - goanpeca
        - mingwandroid
        - nicoddemus
        - ocefpaf
