# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# C:\ci\containers\00001nvk6sa\tmp\build\80754af9\rsync-recipes\navigator-updater-0.2.1-python_3.7-on-winbuilder, last modified Sat Aug 25 00:55:30 2018
# ------------------------------------------------

package:
    name: navigator-updater
    version: 0.2.1
source:
    git_rev: v0.2.1
    git_url: https://github.com/ContinuumIO/navigator-updater.git
build:
    entry_points:
        - navigator-updater = navigator_updater.app.main:main
    osx_is_app: true
    string: py37_0
requirements:
    host:
        - certifi 2018.8.13 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.0.0 py37_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wincertstore 0.2 py37_0
    run:
        - pyqt >=5.6
        - python >=3.7,<3.8.0a0
        - qtpy >=1.2
test:
    commands:
        - navigator-updater --help
    imports:
        - navigator_updater
about:
    home: https://github.com/ContinuumIO/navigator-updater
    license: proprietary - Continuum Analytics, Inc.
    license_family: Proprietary
    summary: Anaconda Navigator Updater
extra:
    copy_test_source_files: true
    final: true
