# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\0000271cl7d\tmp\build\80754af9\rsync-recipes\path.py-11.5.0-python_3.7-on-winbuilder, last modified Tue Oct 16 10:19:06 2018
# ------------------------------------------------

package:
    name: path.py
    version: 11.5.0
source:
    fn: path.py-11.5.0.tar.gz
    sha256: b6687a532a735a2d79a13e92bdb31cb0971abe936ea0fa78bcb47faf4372b3cb
    url: https://pypi.io/packages/source/p/path.py/path.py-11.5.0.tar.gz
build:
    noarch: false
    number: '0'
    script: C:\\ci\\path.py_1539703383683\\_h_env\\python.exe -m pip install --no-deps
        --ignore-installed .
    string: py37_0
requirements:
    host:
        - certifi 2018.10.15 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.4.3 py37_0
        - setuptools_scm 3.1.0 py37h28b3542_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - backports.os
        - importlib_metadata >=0.5
        - python >=3.7,<3.8.0a0
test:
    imports:
        - path
about:
    description: 'path.py implements a path objects as first-class entities, allowing
        common

        operations on files to be invoked on those path objects directly.

        '
    dev_url: https://github.com/jaraco/path.py
    doc_source_url: https://github.com/jaraco/path.py/blob/master/docs/index.rst
    doc_url: https://pathpy.readthedocs.io/en/latest/
    home: https://github.com/jaraco/path.py
    license: MIT
    license_file: LICENSE
    summary: A module wrapper for os.path
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
