# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\kiwisolver-feedstock\recipe, last modified Tue Jul  3 15:49:28 2018
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.0.1
source:
    fn: kiwisolver-1.0.1.tar.gz
    sha256: 8e7fc64fea6d3af96aed63391d35bbbd292a429c8e463277dac839b735503a28
    url: https://github.com/nucleic/kiwi/archive/1.0.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37h6538335_0
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc 14.*
test:
    imports:
        - kiwisolver
about:
    description: 'Kiwi is an implementation of the algorithm based on the seminal

        Cassowary paper.It is not a refactoring of the original C++ solver.

        Kiwi has been designed from the ground up to be lightweight and fast.

        '
    dev_url: https://github.com/nucleic/kiwi
    doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/kiwisolver
    home: https://github.com/nucleic/kiwi
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING.txt
    summary: A fast implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - sccolbert
        - tacaswell
