# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# C:\ci\containers\0000271cm1v\tmp\build\80754af9\rsync-recipes\filelock-3.0.10-python_3.7-on-winbuilder, last modified Fri Nov  2 00:10:38 2018
# ------------------------------------------------

package:
    name: filelock
    version: 3.0.10
source:
    fn: filelock-3.0.10.tar.gz
    sha256: d610c1bb404daf85976d7a82eb2ada120f04671007266b708606565dd03b5be6
    url: https://pypi.io/packages/source/f/filelock/filelock-3.0.10.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - certifi 2018.10.15 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.1 h33f27b4_4
        - setuptools 40.5.0 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.2 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - filelock
about:
    description: 'A filelock provides a synchronisation mechanism between different

        instances of your application, similar to a thread lock. It can be

        used to signalize that files, directories or other resources are

        currently used or manipulated (Think of a sync.lock file). Only the

        existence of the lockfile is watched for this purpose. The file itself

        can not be written and is always empty.

        '
    dev_url: https://github.com/benediktschmitt/py-filelock
    doc_source_url: https://github.com/benediktschmitt/py-filelock/tree/master/docs
    doc_url: https://filelock.readthedocs.io/en/latest/
    home: https://github.com/benediktschmitt/py-filelock
    license: Public Domain
    license_family: Public-Domain
    license_file: LICENSE.rst
    summary: A platform independent file lock.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mariusvniekerk
