# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\00001srktp7\tmp\build\80754af9\rsync-recipes\click-7.0-python_3.7-on-winbuilder, last modified Wed Oct  3 15:35:45 2018
# ------------------------------------------------

package:
    name: click
    version: '7.0'
source:
    sha256: 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7
    url: https://pypi.io/packages/source/C/Click/Click-7.0.tar.gz
build:
    noarch: false
    number: '0'
    script: C:\ci\click_1538599212124\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.2.0 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - click
about:
    description: 'Click is a Python package for creating beautiful command line interfaces

        in a composable way with as little code as necessary.

        '
    dev_url: https://github.com/pallets/click
    doc_source_url: https://github.com/pallets/click/blob/master/docs/index.rst
    doc_url: https://click.palletsprojects.com
    home: https://palletsprojects.com/p/click
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.rst
    summary: Python composable command line interface toolkit
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
