# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000037f87t9\tmp\build\80754af9\rsync-recipes\msgpack-python-0.6.1-cxx_compiler_vs2017-python_3.7-on-winbuilder, last modified Thu Jan 31 09:45:43 2019
# ------------------------------------------------

package:
    name: msgpack-python
    version: 0.6.1
source:
    fn: msgpack-python-0.6.1.tar.gz
    sha256: 4008c72f5ef2b7936447dcb83db41d97e9791c83221be13d5e19db0796df1972
    url: https://pypi.io/packages/source/m/msgpack/msgpack-0.6.1.tar.gz
build:
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37h74a9793_1
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2018.12.5 0
        - certifi 2018.11.29 py37_0
        - cython 0.29.2 py37ha925a31_0
        - openssl 1.1.1a he774522_0
        - pip 18.1 py37_0
        - python 3.7.2 h8c8aaf0_0
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - msgpack
about:
    description: 'MessagePack lets you exchange data among multiple languages like
        JSON.  But

        it is faster and smaller. Small integers are encoded into a single byte and

        typical short strings require only one extra byte in addition to the

        strings themselves.

        '
    dev_url: https://github.com/msgpack/msgpack
    doc_source_url: https://github.com/msgpack/msgpack-python/blob/master/docs/index.rst
    doc_url: http://msgpack-python.readthedocs.io/
    home: http://msgpack.org/
    license: Apache 2.0
    license_family: Apache
    license_file: COPYING
    summary: MessagePack (de)serializer.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pmlandwehr
