# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# C:\ci\containers\000016mo55g\tmp\build\80754af9\rsync-recipes\pandoc-2.2.3.2-on-winbuilder, last modified Mon Aug 27 18:41:36 2018
# ------------------------------------------------

package:
    name: pandoc
    version: 2.2.3.2
source:
    sha256: 8a13f5d81103f5b2af57544b88c24e482d5aecdc1a10c4438c6c4d6d62b3c03c
    url: https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-windows-x86_64.zip
build:
    missing_dso_whitelist:
        - '*'
    number: '0'
    string: '0'
test:
    commands:
        - pandoc --help
        - pandoc --version
about:
    description: 'Pandoc is a Haskell library for converting from one markup format
        to

        another, and a command-line tool that uses this library.

        '
    dev_url: https://github.com/jgm/pandoc
    doc_source_url: https://github.com/jgm/pandoc/tree/master/doc
    doc_url: http://pandoc.org/MANUAL.html
    home: http://pandoc.org/
    license: GPL-2.0
    summary: Universal markup converter (repackaged binaries).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dhimmel
        - jankatins
        - mingwandroid
        - ocefpaf
