# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000037f87q8\tmp\build\80754af9\rsync-recipes\libtiff-4.0.10-c_compiler_vs2017-cxx_compiler_vs2017-on-winbuilder, last modified Mon Jan 28 14:25:53 2019
# ------------------------------------------------

package:
    name: libtiff
    version: 4.0.10
source:
    patches:
        - patches/0001-CVE-2017-11613_part1.patch
        - patches/0002-CVE-2017-11613_part2.patch
        - patches/fix_TIFFReadRawStrip_man_page_typo.patch
        - patches/fixed_lossless_webp_compression_config.patch
    sha256: 2c52d11ccaf767457db0c46795d9c7d1a8d8f76f68b0b800a3dfe45786b996e4
    url: https://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz
build:
    missing_dso_whitelist:
        - /opt/X11/lib/libGL.1.dylib
        - /opt/X11/lib/libglut.3.dylib
    number: '2'
    run_exports:
        - libtiff >=4.0.10,<5.0a0
    string: hb898794_2
requirements:
    build:
        - cmake 3.12.2 he025d50_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - jpeg 9b hb83a4c4_2
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - xz 5.2.4 h2fa13f4_4
        - zlib 1.2.11 h62dcd97_3
        - zstd 1.3.7 h508b16e_0
    run:
        - jpeg >=9b,<10a
        - vc >=14.1,<15.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.3.7,<1.3.8.0a0
test:
    commands:
        - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\tiffxx.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\libtiffxx.dll exit 1
about:
    description: 'This software provides support for the Tag Image File Format (TIFF),
        a

        widely used format for storing image data.

        '
    doc_url: http://www.libtiff.org/document.html
    home: http://www.libtiff.org/
    license: HPND
    license_file: COPYRIGHT
    summary: Support for the Tag Image File Format (TIFF).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - stuarteberg
