# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000029cv55p\tmp\build\80754af9\rsync-recipes\lxml-4.3.2-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Mon Mar 11 10:27:36 2019
# ------------------------------------------------

package:
    name: lxml
    version: 4.3.2
source:
    sha256: 3a9d8521c89bf6f2a929c3d12ad3ad7392c774c327ea809fd08a13be6b3bc05f
    url: https://pypi.io/packages/source/l/lxml/lxml-4.3.2.tar.gz
build:
    number: '0'
    script:
        - python -m pip install --no-deps --ignore-installed .
    string: py37h1350720_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - cython 0.29.5 py37ha925a31_0
        - libiconv 1.15 h1df5818_7
        - libxml2 2.9.9 h464c3ec_0
        - libxslt 1.1.33 h579f668_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - libxml2 >=2.9.9,<2.10.0a0
        - libxslt >=1.1.33,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - lxml
        - lxml.etree
        - lxml.objectify
about:
    description: 'The lxml XML toolkit is a Pythonic binding for the C libraries libxml2
        and

        libxslt. It is unique in that it combines the speed and XML feature

        completeness of these libraries with the simplicity of a native Python API,

        mostly compatible but superior to the well-known ElementTree API.

        '
    dev_url: https://github.com/lxml/lxml
    doc_source_url: https://github.com/lxml/lxml/tree/master/doc
    doc_url: http://lxml.de/index.html#documentation
    home: http://lxml.de/
    license: BSD 3-Clause, GPL-2.0, ZPL-2.0, and ElementTree
    license_file: LICENSES.txt
    summary: Pythonic binding for the C libraries libxml2 and libxslt.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - ocefpaf
