# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\toolz-feedstock\recipe, last modified Tue Jul  3 15:55:58 2018
# ------------------------------------------------

package:
    name: toolz
    version: 0.9.0
source:
    fn: toolz-0.9.0.tar.gz
    sha256: 929f0a7ea7f61c178bd951bdae93920515d3fbdbafc8e6caf82d752b9b3b31c9
    url: https://pypi.io/packages/source/t/toolz/toolz-0.9.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - toolz
        - toolz.curried
        - toolz.sandbox
about:
    description: 'Toolz provides a set of utility functions for iterators, functions,
        and

        dictionaries. These functions interoperate well and form the building

        blocks of common data analytic operations. They extend the standard

        libraries itertools and functools and borrow heavily from the standard

        libraries of contemporary functional languages.

        '
    dev_url: https://github.com/pytoolz/toolz
    doc_source_url: https://github.com/pytoolz/toolz/blob/master/doc/source/index.rst
    doc_url: http://toolz.readthedocs.org/en/latest/
    home: http://toolz.readthedocs.org/
    license: BSD 3-Clause
    summary: A functional standard library for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - eriknw
        - jakirkham
        - jcrist
        - mrocklin
