# This file created by conda-build 3.15.1
# ------------------------------------------------

package:
    name: vs2015_runtime
    version: 14.15.26706
build:
    no_link:
        - '*.dll

            '
        - Library/bin/*.dll
    number: 0
    string: h3a45250_0
about:
    summary: MSVC runtimes associated with cl.exe version 19.15.26726 (VS 2017 update
        8)
extra:
    copy_test_source_files: true
    final: true
