# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\00001vskhjt\tmp\build\80754af9\rsync-recipes\conda-verify-3.1.1-python_3.7-on-winbuilder, last modified Wed Oct  3 09:34:01 2018
# ------------------------------------------------

package:
    name: conda-verify
    version: 3.1.1
source:
    fn: conda-verify-3.1.1.tar.gz
    sha256: 2697f5525f0b33b5e6fb288db0f6e72a4b895492ee344e8795c6de7f64dbd2a0
    url: https://github.com/conda/conda-verify/archive/3.1.1.tar.gz
build:
    number: '0'
    script: C:\\ci\\conda-verify_1538577409397\\_h_env\\python.exe setup.py install
        --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - python 3.7.0 hea74fb7_0
        - setuptools 40.2.0 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - click
        - future
        - jinja2
        - python >=3.7,<3.8.0a0
        - pyyaml
        - six
test:
    imports:
        - conda_verify
about:
    description: 'conda-verify is a tool for (passively) verifying conda recipes and
        conda

        packages.

        '
    home: https://github.com/conda/conda-verify
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: tool for validating conda recipes and conda packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mandeep
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
