# This file created by conda-build 3.17.6
# meta.yaml template originally from:
# C:\ci\containers\00002gc3h3s\tmp\build\80754af9\rsync-recipes\pillow-5.4.1-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Fri Jan 11 16:13:27 2019
# ------------------------------------------------

package:
    name: pillow
    version: 5.4.1
source:
    sha256: 5233664eadfa342c639b9b9977190d64ad7aca4edc51a966394d7e08e7f38a9f
    url: https://pypi.io/packages/source/P/Pillow/Pillow-5.4.1.tar.gz
build:
    number: '0'
    string: py37hdc69c19_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - freetype 2.9.1 ha9979f8_1
        - jpeg 9b hb83a4c4_2
        - libpng 1.6.36 h2a8f88b_0
        - libtiff 4.0.9 h36446d0_2
        - openssl 1.1.1a he774522_0
        - pip 18.1 py37_0
        - python 3.7.2 h8c8aaf0_0
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 he774522_0
        - tk 8.6.8 hfa6e2cd_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - freetype >=2.9.1,<3.0a0
        - jpeg >=9b,<10a
        - libtiff >=4.0.9,<5.0a0
        - olefile
        - python >=3.7,<3.8.0a0
        - tk >=8.6.8,<8.7.0a0
        - vc >=14.1,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    imports:
        - PIL
        - PIL.Image
        - PIL._imaging
        - PIL._imagingft
        - PIL._imagingmath
        - PIL._imagingmorph
about:
    description: 'Pillow is the friendly PIL fork. PIL is the Python Imaging Library,

        adds image processing capabilities to your Python interpreter.

        '
    dev_url: https://github.com/python-pillow/Pillow
    doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
    doc_url: http://pillow.readthedocs.io/en/4.2.x/
    home: https://pillow.readthedocs.io
    license: PIL
    license_file: LICENSE
    summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - patricksnape
        - pelson
