# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001s41olp\tmp\build\80754af9\rsync-recipes\imageio-2.5.0-python_3.7-on-winbuilder, last modified Mon Feb 25 15:14:25 2019
# ------------------------------------------------

package:
    name: imageio
    version: 2.5.0
source:
    fn: imageio-2.5.0.tar.gz
    sha256: 42e65aadfc3d57a1043615c92bdf6319b67589e49a0aae2b985b82144aceacad
    url: https://pypi.io/packages/source/i/imageio/imageio-2.5.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - openssl 1.1.1a he774522_0
        - python 3.7.2 h8c8aaf0_10
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - numpy
        - pillow
        - python >=3.7,<3.8.0a0
test:
    imports:
        - imageio
about:
    dev_url: https://github.com/imageio/imageio
    doc_url: http://imageio.readthedocs.io
    home: http://imageio.github.io
    license: BSD 2-Clause
    license_file: LICENSE
    summary: a Python library for reading and writing image data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - almarklein
        - blink1073
        - jni
