# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# C:\ci\containers\00001hdkbhd\tmp\build\80754af9\rsync-recipes\patsy-0.5.1-python_3.7-on-winbuilder, last modified Wed Oct 31 09:30:03 2018
# ------------------------------------------------

package:
    name: patsy
    version: 0.5.1
source:
    sha256: f115cec4201e1465cd58b9866b0b0e7b941caafec129869057405bfe5b5e3991
    url: https://pypi.io/packages/source/p/patsy/patsy-0.5.1.tar.gz
build:
    number: '0'
    script:
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.10.15 py37_0
        - python 3.7.1 h33f27b4_4
        - setuptools 40.4.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - numpy >=1.4.0
        - python >=3.7,<3.8.0a0
        - scipy
        - six
test:
    imports:
        - patsy
about:
    description: 'Patsy is a Python library for describing statistical models (especially

        linear models, or models that have a linear component) and building design

        matrices.

        '
    dev_url: https://github.com/pydata/patsy
    doc_source_url: https://github.com/pydata/patsy/blob/master/doc/index.rst
    doc_url: http://patsy.readthedocs.org/en/latest/
    home: https://github.com/pydata/patsy
    license: BSD-2-Clause, PSF2
    license_family: BSD
    license_file: LICENSE.txt
    summary: Describing statistical models in Python using symbolic formulas
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - croth1
