# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\00001srkti7\tmp\build\80754af9\rsync-recipes\python-libarchive-c-2.8-python_3.7-on-winbuilder, last modified Sun Sep 30 06:16:19 2018
# ------------------------------------------------

package:
    name: python-libarchive-c
    version: '2.8'
source:
    fn: python-libarchive-c-2.8.tar.gz
    patches:
        - 0001-Add-zstd-support.patch
        - 0002-Export-ArchiveWrite.patch
    sha256: 06d44d5b9520bdac93048c72b7ed66d11a6626da16d2086f9aad079674d8e061
    url: https://pypi.io/packages/source/l/libarchive-c/libarchive-c-2.8.tar.gz
build:
    number: '6'
    string: py37_6
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - python 3.7.0 hea74fb7_0
        - setuptools 40.2.0 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - libarchive
        - python >=3.7,<3.8.0a0
test:
    imports:
        - libarchive
about:
    home: https://github.com/Changaco/python-libarchive-c
    license: CC0-1.0
    summary: Python interface to libarchive
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - mingwandroid
