# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003270m4b\tmp\build\80754af9\rsync-recipes\scikit-image-0.14.2-python_3.7-cxx_compiler_vs2017-c_compiler_vs2017-on-winbuilder, last modified Wed Mar 13 13:00:55 2019
# ------------------------------------------------

package:
    name: scikit-image
    version: 0.14.2
source:
    git_rev: v0.14.2
    git_url: https://github.com/scikit-image/scikit-image
build:
    entry_points:
        - skivi = skimage.scripts.skivi:main
    number: '0'
    script:
        - rm -rf skimage/viewer/tests
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py37ha925a31_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - cython 0.29.6 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - mkl 2019.1 144
        - numpy 1.11.3 py37h35d8231_12
        - numpy-base 1.11.3 py37hc3f5095_12
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - scipy 1.2.1 py37h29ff71c_0
        - setuptools 40.8.0 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - cloudpickle >=0.2.1
        - cytoolz >=0.7.3
        - dask-core >=0.9.0
        - imageio >=2.1.0
        - matplotlib >=2.0.0
        - networkx >=1.8
        - numpy >=1.11.3,<2.0a0
        - pillow >=4.3.0
        - python >=3.7,<3.8.0a0
        - pywavelets >=0.4.0
        - scipy >=0.17
        - six >=1.7.3
        - toolz >=0.7.4
        - vc >=14.1,<15.0a0
test:
    commands:
        - setx MPLBACKEND "Agg"
        - pytest --pyargs skimage
    imports:
        - skimage
    requires:
        - numpy 1.11.*
        - pytest
        - pytest-cov
about:
    home: http://scikit-image.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Image processing routines for SciPy.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Korijn
        - ivoflipse
        - jakirkham
        - jni
        - mingwandroid
        - msarahan
        - ocefpaf
        - soupault
