# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\send2trash-feedstock\recipe, last modified Tue Jul  3 15:55:01 2018
# ------------------------------------------------

package:
    name: send2trash
    version: 1.5.0
source:
    fn: Send2Trash-1.5.0.tar.gz
    sha256: 60001cc07d707fe247c94f74ca6ac0d3255aabcb930529690897ca2a39db28b2
    url: https://pypi.io/packages/source/S/Send2Trash/Send2Trash-1.5.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    build:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - echo test > test.txt
        - python -c "from send2trash import *; send2trash('test.txt')"
    imports:
        - send2trash
about:
    home: https://github.com/hsoft/send2trash
    license: BSD-3-Clause
    license_family: BSD
    license_file: C:\Users\builder\conda\aggregate\send2trash-feedstock\recipe/LICENSE
    summary: Python library to natively send files to Trash (or Recycle bin) on all
        platforms.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
