# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# C:\ci\containers\00002mf1bdj\tmp\build\80754af9\rsync-recipes\anaconda-client-1.7.2-python_3.7-on-winbuilder, last modified Wed Aug 29 14:19:49 2018
# ------------------------------------------------

package:
    name: anaconda-client
    version: 1.7.2
source:
    git_rev: 1.7.2
    git_url: https://github.com/Anaconda-Platform/anaconda-client.git
build:
    entry_points:
        - anaconda = binstar_client.scripts.cli:main
    string: py37_0
requirements:
    host:
        - asn1crypto 0.24.0 py37_0
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - cffi 1.11.5 py37h74b6da3_1
        - chardet 3.0.4 py37_1
        - clyent 1.2.2 py37_1
        - cryptography 2.3.1 py37h74b6da3_0
        - decorator 4.3.0 py37_0
        - idna 2.7 py37_0
        - ipython_genutils 0.2.0 py37_0
        - jsonschema 2.6.0 py37_0
        - jupyter_core 4.4.0 py37_0
        - nbformat 4.4.0 py37_0
        - openssl 1.0.2p hfa6e2cd_0
        - pycparser 2.18 py37_1
        - pyopenssl 18.0.0 py37_0
        - pysocks 1.6.8 py37_0
        - python 3.7.0 hea74fb7_0
        - python-dateutil 2.7.3 py37_0
        - pytz 2018.5 py37_0
        - pyyaml 3.13 py37hfa6e2cd_0
        - requests 2.19.1 py37_0
        - setuptools 40.2.0 py37_0
        - six 1.11.0 py37_1
        - traitlets 4.3.2 py37_0
        - urllib3 1.23 py37_0
        - vc 14.1 h21ff451_3
        - vs2015_runtime 15.5.2 3
        - win_inet_pton 1.0.1 py37_1
        - wincertstore 0.2 py37_0
        - yaml 0.1.7 hc54c509_2
    run:
        - clyent >=1.2.2
        - nbformat
        - python >=3.7,<3.8.0a0
        - python-dateutil
        - pytz
        - pyyaml
        - requests >=2.9.1
        - setuptools
test:
    commands:
        - anaconda -h
        - anaconda --version
    imports:
        - binstar_client
        - binstar_client.scripts.cli
    requires:
        - conda
about:
    description: 'Anaconda-client is used to connect to and manage your Anaconda Cloud
        account, upload packages you have created

        and generate access tokens to allow access to private packages.

        '
    dev_url: https://github.com/Anaconda-Platform/anaconda-client
    doc_source_url: https://github.com/Anaconda-Platform/anaconda-client/blob/develop/README.md
    doc_url: https://docs.continuum.io/anaconda-cloud/cli
    home: http://anaconda.org
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE.md
    summary: anaconda.org command line client library
extra:
    copy_test_source_files: true
    final: true
