# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-gcc-libs, last modified Mon Dec 19 01:03:47 2016
# ------------------------------------------------

package:
    name: m2w64-gcc-libs
    version: 5.3.0
source:
    md5: 4698350ad11d86459ffc4843fe1c951f
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-gcc-libs-5.3.0-5.src.tar.gz
build:
    number: '7'
    string: '7'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-gmp
        - m2w64-gcc-libs-core
        - m2w64-gcc-libgfortran
        - m2w64-libwinpthread-git
about:
    home: https://gcc.gnu.org
    license: GPL3+, partial:GCCRLE, partial:LGPL2+
    summary: GNU Compiler Collection (libraries) for MinGW-w64
extra:
    msys2-binaries:
        win-32:
            md5: f0e867e51a73dc66929d5bdafe17c1cf
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            patches:
                - 0001-mingw32-Remove-gcc-libs-core.patch
            srcpkg: mingw32/mingw-w64-i686-gcc-libs
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-gcc-libs-5.3.0-5-any.pkg.tar.xz
        win-64:
            md5: 071cd392ca1e2e15fe1612b925bd5172
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            patches:
                - 0001-mingw64-Remove-gcc-libs-core.patch
            srcpkg: mingw64/mingw-w64-x86_64-gcc-libs
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-gcc-libs-5.3.0-5-any.pkg.tar.xz
