# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# C:\ci\containers\00003r3dp6l\tmp\build\80754af9\rsync-recipes\freetype-2.9.1-c_compiler_vs2015-on-winbuilder, last modified Thu Jul 26 15:45:58 2018
# ------------------------------------------------

package:
    name: freetype
    version: 2.9.1
source:
    fn: freetype-2.9.1.tar.bz2
    patches:
        - 0001-Unbreak-CMake-Windows-installation.patch
        - 0002-Win-Specify-RUNTIME-destination-for-dll.patch
    sha256: db8d87ea720ea9d5edc5388fc7a0497bb11ba9fe972245e0f7f4c7e8b1e1e84d
    url: http://download.savannah.gnu.org/releases/freetype/freetype-2.9.1.tar.bz2
build:
    number: '1'
    run_exports:
        - freetype >=2.9.1,<3.0a0
    string: ha9979f8_1
requirements:
    build:
        - cmake 3.11.1 h0c2ffe5_1
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - libpng 1.6.34 h79bbb47_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - zlib 1.2.11 h8395fce_2
    run:
        - libpng >=1.6.34,<1.7.0a0
        - vc 14.*
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - if exist %LIBRARY_BIN%\freetype.dll (exit 0) else (exit 1)
about:
    description: 'FreeType is designed to be small, efficient, highly customizable

        and portable while capable of producing high-quality output (glyph images)

        of most vector and bitmap font formats.

        '
    dev_url: http://git.savannah.gnu.org/cgit/freetype/
    doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
    doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
    home: https://www.freetype.org/
    license: GPL-2.0 and FreeType
    license_url: http://freetype.sourceforge.net/FTL.TXT
    summary: A Free, High-Quality, and Portable Font Engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - msarahan
        - ocefpaf
