# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\terminado-feedstock\recipe, last modified Tue Jul  3 15:55:46 2018
# ------------------------------------------------

package:
    name: terminado
    version: 0.8.1
source:
    sha256: 55abf9ade563b8f9be1f34e4233c7b7bde726059947a593322e8a553cc4c067a
    url: https://pypi.io/packages/source/t/terminado/terminado-0.8.1.tar.gz
build:
    number: '1'
    script: python setup.py install
    string: py37_1
requirements:
    host:
        - python 3.7.0 hea74fb7_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
    run:
        - python >=3.7,<3.8.0a0
        - pywinpty
        - tornado >=4
test:
    commands:
        - nosetests terminado
    imports:
        - terminado
    requires:
        - nose
        - posix
about:
    description: 'Terminado is a Tornado websocket backend for the term.js Javascript

        terminal emulator library.

        '
    dev_url: https://github.com/takluyver/terminado
    doc_source_url: https://github.com/takluyver/terminado/blob/master/doc/index.rst
    doc_url: http://terminado.readthedocs.org/en/latest/
    home: https://github.com/jupyter/terminado
    license: BSD 2-clause
    summary: Terminals served by tornado websockets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pelson
        - takluyver
