# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\sphinxcontrib-feedstock\recipe, last modified Tue Jul  3 15:31:35 2018
# ------------------------------------------------

package:
    name: sphinxcontrib
    version: '1.0'
build:
    number: '1'
    string: py37_1
requirements:
    build:
        - python 3.7.0 hea74fb7_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - sphinxcontrib
about:
    license: BSD
    summary: Python namespace for sphinxcontrib
extra:
    copy_test_source_files: true
    final: true
