# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\_ipyw_jlab_nb_ext_conf-feedstock\recipe, last modified Tue Jul  3 15:31:32 2018
# ------------------------------------------------

package:
    name: _ipyw_jlab_nb_ext_conf
    version: 0.1.0
build:
    always_include_files:
        - etc/jupyter/jupyter_notebook_config.json
        - etc/jupyter/nbconfig/notebook.json
    number: '0'
    string: py37_0
requirements:
    host:
        - backcall 0.1.0 py37_0
        - bleach 2.1.3 py37_0
        - certifi 2018.4.16 py37_0
        - colorama 0.3.9 py37_0
        - decorator 4.3.0 py37_0
        - entrypoints 0.2.3 py37_2
        - html5lib 1.0.1 py37_0
        - ipykernel 4.8.2 py37_0
        - ipython 6.4.0 py37_1
        - ipython_genutils 0.2.0 py37_0
        - ipywidgets 7.2.1 py37_0
        - jedi 0.12.0 py37_1
        - jinja2 2.10 py37_0
        - jsonschema 2.6.0 py37_0
        - jupyter_client 5.2.3 py37_0
        - jupyter_core 4.4.0 py37_0
        - jupyterlab 0.32.1 py37_0
        - jupyterlab_launcher 0.11.0 py37_0
        - libsodium 1.0.16 h9d3ae62_0
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gmp 6.1.0 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - markupsafe 1.0 py37hfa6e2cd_1
        - mistune 0.8.3 py37hfa6e2cd_1
        - msys2-conda-epoch 20160418 1
        - nbconvert 5.3.1 py37_0
        - nbformat 4.4.0 py37_0
        - notebook 5.5.0 py37_0
        - pandoc 2.2.1 h1a437c5_0
        - pandocfilters 1.4.2 py37_1
        - parso 0.2.1 py37_0
        - pickleshare 0.7.4 py37_0
        - prompt_toolkit 1.0.15 py37_0
        - pygments 2.2.0 py37_0
        - python 3.7.0 hea74fb7_0
        - python-dateutil 2.7.3 py37_0
        - pywinpty 0.5.4 py37_0
        - pyzmq 17.0.0 py37hfa6e2cd_3
        - send2trash 1.5.0 py37_0
        - setuptools 39.2.0 py37_0
        - simplegeneric 0.8.1 py37_2
        - six 1.11.0 py37_1
        - terminado 0.8.1 py37_1
        - testpath 0.3.1 py37_0
        - tornado 5.0.2 py37hfa6e2cd_0
        - traitlets 4.3.2 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wcwidth 0.1.7 py37_0
        - webencodings 0.5.1 py37_1
        - widgetsnbextension 3.2.1 py37_0
        - wincertstore 0.2 py37_0
        - winpty 0.4.3 4
        - zeromq 4.2.5 he025d50_1
    run:
        - ipywidgets
        - jupyterlab
        - python >=3.7,<3.8.0a0
        - widgetsnbextension
test:
    commands:
        - jupyter-nbextension list
        - jupyter-serverextension list
about:
    home: https://github.com/ContinuumIO/anaconda-nb-extensions-meta-config
    license: BSD
    summary: A configuration metapackage for enabling Anaconda-bundled jupyter extensions
extra:
    copy_test_source_files: true
    final: true
