# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\jinja2-feedstock\recipe, last modified Tue Jul  3 15:49:08 2018
# ------------------------------------------------

package:
    name: jinja2
    version: '2.10'
source:
    fn: Jinja2-2.10.tar.gz
    sha256: f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4
    url: https://pypi.io/packages/source/J/Jinja2/Jinja2-2.10.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - markupsafe >=0.23
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    imports:
        - jinja2
about:
    description: 'Jinja2 is a full featured template engine for Python. It has full
        unicode

        support, an optional integrated sandboxed execution environment, widely

        used and BSD licensed.

        '
    dev_url: https://github.com/pallets/jinja
    doc_source_url: https://github.com/pallets/jinja/blob/master/docs/index.rst
    doc_url: http://jinja.pocoo.org/docs/dev/
    home: http://jinja.pocoo.org
    license: 3-Clause BSD
    license_file: LICENSE
    summary: An easy to use stand-alone template engine written in pure python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - nehaljwani
        - scopatz
