# This file created by conda-build 3.17.8
# ------------------------------------------------

package:
    name: numpy-base
    version: 1.16.2
source:
    -   patches:
            - 0001-fix-windows-case-sensitivity.patch
            - 0002-simplify-arch-flags.patch
            - 0003-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
            - 0004-disable-memmap-filename-test-due-to-CI-link-confusio.patch
            - 0005-disable-broken-tests.patch
            - 0006-use-mklfft-when-available.patch
            - 0007-define-mkl_version-in-__init__.py.patch
            - 0008-intel-umath-optimizations.patch
            - 0009-intel-mkl_mem-all.patch
            - 0010-intel-init_mkl.patch
            - 0011-intel-mkl_random.patch
            - 0012-Remove-ICC-specific-flags.patch
            - 0013-Remove-np.invsqrt.patch
            - 0014-Rewrite-inlining.patch
            - 0015-Fixes-from-Intel-Distribution.patch
            - 0016-define-__THRESHOLD.patch
            - 0017-mark-known-failing-tests-on-ppc64le.patch
            - 0018-filter-out-warnings-when-importing-mkl_fft.patch
        sha256: 6c692e3879dde0b67a9dc78f9bfb6f61c666b4562fd8619632d7043fb5b691b0
        url: https://pypi.io/packages/source/n/numpy/numpy-1.16.2.zip
    -   folder: mkl_random
        sha256: 2270ef2834f6552850533aad01500d27c8e056f2cfbdbdb751593000aea1159e
        url: https://github.com/IntelPython/mkl_random/archive/v1.0.2.tar.gz
    -   folder: mkl_fft
        sha256: 3c7ed29e203c5b664ecafb11d767d62f9cae4aa56f9a95737e121192a66673bf
        url: https://github.com/IntelPython/mkl_fft/archive/v1.0.6.tar.gz
build:
    force_use_keys:
        - python
    noarch: false
    number: '0'
    script: install_base.bat
    string: py37hc3f5095_0
requirements:
    build:
        - intel-fortran_win-64 2019.0.0 hf4e3f46_1
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - cython 0.29.5 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - mkl 2019.1 144
        - mkl-devel 2019.1 145
        - mkl-include 2019.1 144
        - openssl 1.1.1b he774522_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - blas 1.0 mkl
        - icc_rt >=2019.0.0
        - mkl >=2019.1,<2020.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    commands:
        - IF NOT EXIST %SP_DIR%\numpy\distutils\site.cfg exit 1
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
