# This file created by conda-build 3.16.0
# meta.yaml template originally from:
# C:\ci\containers\00003f294n3\tmp\build\80754af9\rsync-recipes\jupyterlab_server-0.2.0-python_3.7-on-winbuilder, last modified Tue Oct  9 09:22:39 2018
# ------------------------------------------------

package:
    name: jupyterlab_server
    version: 0.2.0
source:
    fn: jupyterlab_server-0.2.0.tar.gz
    sha256: 72d916a73957a880cdb885def6d8664a6d1b2760ef5dca5ad665aa1e8d1bb783
    url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-0.2.0.tar.gz
build:
    number: '0'
    script: C:\ci\jupyterlab_server_1539095114932\_h_env\python.exe -m pip install
        . --no-deps --ignore-installed -vvv
    string: py37_0
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.4.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.0 py37_0
        - wincertstore 0.2 py37_0
    run:
        - notebook
        - python >=3.7,<3.8.0a0
test:
    imports:
        - jupyterlab_server
about:
    home: http://github.com/jupyterlab/jupyterlab_server
    license: BSD 3-Clause
    license_file: LICENSE
    summary: A set of server components for JupyterLab and JupyterLab like applications.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - afshin
        - blink1073
        - jasongrout
