# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\00003f294mq\tmp\build\80754af9\rsync-recipes\jupyter_console-6.0.0-python_3.7-on-winbuilder, last modified Mon Oct  8 13:50:08 2018
# ------------------------------------------------

package:
    name: jupyter_console
    version: 6.0.0
source:
    sha256: 308ce876354924fb6c540b41d5d6d08acfc946984bf0c97777c1ddcb42e0b2f5
    url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-6.0.0.tar.gz
build:
    entry_points:
        - jupyter-console = jupyter_console.app:main
    number: '0'
    script: C:\ci\jupyter_console_1539024794455\_h_env\python.exe -m pip install .
        --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.4.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.0 py37_0
        - wincertstore 0.2 py37_0
    run:
        - ipykernel
        - ipython
        - jupyter_client
        - prompt_toolkit >=2.0.0,<2.1.0
        - pygments
        - python >=3.7,<3.8.0a0
test:
    commands:
        - jupyter-console -h
    imports:
        - jupyter_console
about:
    description: 'Jupyter console is a terminal frontend for kernels using the Jupyter
        protocol.

        '
    dev_url: https://github.com/jupyter/jupyter_console
    doc_source_url: https://github.com/jupyter/jupyter_console/blob/master/docs/index.rst
    doc_url: http://jupyter-console.readthedocs.org/
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: COPYING.md
    summary: Jupyter terminal console
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
