# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\asn1crypto-feedstock\recipe, last modified Tue Jul  3 15:45:10 2018
# ------------------------------------------------

package:
    name: asn1crypto
    version: 0.24.0
source:
    fn: asn1crypto-0.24.0.tar.gz
    sha256: 9d5c20441baf0cb60a4ac34cc447c6c189024b6b4c6cd7877034f4965c464e49
    url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-0.24.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - asn1crypto
about:
    dev_url: https://github.com/wbond/asn1crypto
    doc_url: https://github.com/wbond/asn1crypto#documentation
    home: https://github.com/wbond/asn1crypto
    license: MIT
    license_file: LICENSE
    summary: Python ASN.1 library with a focus on performance and a pythonic API
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
