# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000029cv5eb\tmp\build\80754af9\rsync-recipes\matplotlib-3.0.3-c_compiler_vs2017-python_3.7-cxx_compiler_vs2017-on-winbuilder, last modified Thu Mar 14 06:35:05 2019
# ------------------------------------------------

package:
    name: matplotlib
    version: 3.0.3
source:
    patches:
        - cfg_qt5agg.patch
        - setupext.patch
    sha256: d384a58409c1c23b8760b6f3d84ebed2c936df7dcb82797e983faaf30ae4d69d
    url: https://github.com/matplotlib/matplotlib/archive/v3.0.3.tar.gz
build:
    ignore_run_exports:
        - pyqt
    number: '0'
    string: py37hc8f65d3_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - cycler 0.10.0 py37_0
        - freetype 2.9.1 ha9979f8_1
        - icc_rt 2019.0.0 h0cc432a_1
        - icu 58.2 ha66f8fd_1
        - intel-openmp 2019.1 144
        - jpeg 9b hb83a4c4_2
        - libpng 1.6.36 h2a8f88b_0
        - mkl 2019.1 144
        - msinttypes r26 h7e1a5f4_2
        - nose 1.3.7 py37_2
        - numpy 1.11.3 py37h35d8231_12
        - numpy-base 1.11.3 py37hc3f5095_12
        - openssl 1.1.1b he774522_1
        - pyparsing 2.3.1 py37_0
        - pyqt 5.9.2 py37h6538335_2
        - python 3.7.2 h8c8aaf0_10
        - python-dateutil 2.8.0 py37_0
        - pytz 2018.9 py37_0
        - qt 5.9.7 vc14h73c81de_0
        - setuptools 40.8.0 py37_0
        - sip 4.19.8 py37h6538335_0
        - six 1.12.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - cycler >=0.10
        - freetype >=2.9.1,<3.0a0
        - kiwisolver
        - libpng >=1.6.36,<1.7.0a0
        - numpy
        - pyparsing
        - pyqt 5.9.*
        - python >=3.7,<3.8.0a0
        - python-dateutil
        - pytz
        - setuptools
        - tornado
        - vc >=14.1,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    imports:
        - matplotlib
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.ft2font
        - matplotlib.pyplot
        - matplotlib.ttconv
        - mpl_toolkits
        - pylab
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
