# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003cheg79\tmp\build\80754af9\rsync-recipes\python-3.7.3-cxx_compiler_vs2017-c_compiler_vs2017-vc_14-on-winbuilder, last modified Wed Mar 27 15:13:18 2019
# ------------------------------------------------

package:
    name: python
    version: 3.7.3
source:
    -   patches:
            - 0001-Add-Anaconda-Distribution-version-logic.patch
            - 0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - 0003-Win32-distutils-Also-look-for-executable.bat.patch
            - 0004-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - 0005-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - 0006-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - 0007-Support-cross-compiling-byte-code.patch
            - 0008-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - 0009-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - 0010-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - 0011-Win32-Do-not-download-externals.patch
            - 0012-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - 0013-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - 0014-Disable-new-dtags-in-unixccompiler.py.patch
            - 0015-Fix-cross-compilation-on-Debian-based-distros.patch
            - 0016-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
            - 0017-Unvendor-openssl.patch
            - 0018-Unvendor-sqlite3.patch
            - 0019-venv-Revert-a-change-from-https-github.com-python-cp.patch
            - 0020-Add-CondaEcosystemModifyDllSearchPath.patch
        sha256: da60b54064d4cfcd9c26576f6df2690e62085123826cff2e667e72a91952d318
        url: https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
    -   folder: externals/xz-5.2.2
        sha256: 02b6d6f1e0369940e7e1f0d324992e069d09f5f3d32d86e2d22cd8b82ac3fb3f
        url: https://github.com/python/cpython-source-deps/archive/xz-5.2.2.zip
    -   folder: externals/tcl-core-8.6.9.0
        sha256: ea9e724536ec13b476ebbd47948303b92fdd90a33aa94f30fcc2f5c3a899f69e
        url: https://github.com/python/cpython-source-deps/archive/tcl-core-8.6.9.0.zip
    -   folder: externals/tk-8.6.9.0
        sha256: f3112b6bbc3bd163c877030187e73ce9a113ce03eff559ec5b9df697e3a08fad
        url: https://github.com/python/cpython-source-deps/archive/tk-8.6.9.0.zip
    -   folder: externals/tcltk-8.6.9.0
        sha256: 37cd629a75d2a34974a3d771ccab5c9e3caf3d138cea81040f9cdba1aded1cf2
        url: https://github.com/python/cpython-bin-deps/archive/tcltk-8.6.9.0.zip
    -   folder: externals/tix-8.4.3.6
        sha256: e558e3dc5e67ac0942f8fceafce00ca46b177da9ebeaf38ec7fafd9b9913ac56
        url: https://github.com/python/cpython-source-deps/archive/tix-8.4.3.6.zip
    -   folder: externals/bzip2-1.0.6
        sha256: c42fd1432a2667b964a74bc423bb7485059c4a6d5dc92946d59dbf9a6bdb988d
        url: https://github.com/python/cpython-source-deps/archive/bzip2-1.0.6.zip
    -   folder: externals/zlib-1.2.11
        sha256: debb1952945fa6c25817a40abe90641b572c83171f244937b70b9fe156f5a63a
        url: https://github.com/python/cpython-source-deps/archive/zlib-1.2.11.zip
    -   folder: externals/nasm-2.11.06
        sha256: de3c87b26a80e789986d8e6950c6304175d3829afe9c6c7211eb7257266ab0ac
        url: https://github.com/python/cpython-bin-deps/archive/nasm-2.11.06.zip
build:
    no_link:
        - DLLs/_ctypes.pyd
    number: '0'
    string: h8c8aaf0_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2019.1.23 0
        - openssl 1.1.1b he774522_1
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - openssl >=1.1.1b,<1.1.2a
        - sqlite >=3.27.2,<4.0a0
        - vc >=14.1,<15.0a0
test:
    commands:
        - python -V
        - 2to3 -h
        - pydoc -h
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
