# This file created by conda-build 3.0.28
# meta.yaml template originally from:
# C:\ci\containers\00000a6tbva\tmp\build\80754af9\rsync-recipes\jpeg-9b-c_compilervs2015-on-winbuilder, last modified Wed Nov  8 20:31:19 2017
# ------------------------------------------------

package:
    name: jpeg
    version: 9b
source:
    md5: 6a9996ce116ec5c52b4870dbcd6d3ddb
    patches:
        - CMakeLists.txt.patch
    url: http://www.ijg.org/files/jpegsrc.v9b.tar.gz
build:
    number: '2'
    run_exports:
        - jpeg >=9b,<10a
    string: hb83a4c4_2
requirements:
    build:
        - cmake-binary 3.9.1 h5f8252f_0
        - vs2015_win-64 14.0.25123 hf5d5b87_2
    run:
        - vc 14.*
test:
    commands:
        - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg
    files:
        - testorig.jpg
about:
    home: http://www.ijg.org/
    license: Custom free software license
    summary: read/write jpeg COM, EXIF, IPTC medata
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - jakirkham
        - msarahan
