# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000am8gb3\tmp\build\80754af9\rsync-recipes\wrapt-1.11.1-python_3.7-c_compiler_vs2017-on-winbuilder, last modified Wed Feb  6 09:33:03 2019
# ------------------------------------------------

package:
    name: wrapt
    version: 1.11.1
source:
    sha256: 4aea003270831cceb8a90ff27c4031da6ead7ec1886023b80ce0dfe0adf61533
    url: https://pypi.io/packages/source/w/wrapt/wrapt-1.11.1.tar.gz
build:
    number: '0'
    script: C:\ci\wrapt_1549642713801\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_0
        - setuptools 40.7.3 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - wrapt
about:
    description: 'The aim of the wrapt module is to provide a transparent object proxy
        for

        Python, which can be used as the basis for the construction of function

        wrappers and decorator functions.

        '
    dev_url: https://github.com/GrahamDumpleton/wrapt
    doc_source_url: https://github.com/GrahamDumpleton/wrapt/blob/master/docs/index.rst
    doc_url: http://wrapt.readthedocs.org/en/latest/
    home: https://github.com/GrahamDumpleton/wrapt
    license: BSD 2-Clause
    license_file: LICENSE
    summary: Module for decorators, wrappers and monkey patching
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
        - ocefpaf
