# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\chardet-feedstock\recipe, last modified Tue Jul  3 15:46:05 2018
# ------------------------------------------------

package:
    name: chardet
    version: 3.0.4
source:
    fn: chardet-3.0.4.tar.gz
    sha256: 84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae
    url: https://pypi.io/packages/source/c/chardet/chardet-3.0.4.tar.gz
build:
    entry_points:
        - chardetect = chardet.cli.chardetect:main
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_1
requirements:
    host:
        - atomicwrites 1.1.5 py37_0
        - attrs 18.1.0 py37_0
        - certifi 2018.4.16 py37_0
        - colorama 0.3.9 py37_0
        - more-itertools 4.2.0 py37_0
        - pluggy 0.6.0 py37_0
        - py 1.5.3 py37_0
        - pytest 3.6.2 py37_0
        - pytest-runner 4.2 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - six 1.11.0 py37_1
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - chardetect --help
    imports:
        - chardet
about:
    description: 'chardet is a character encoding auto-detector in Python.

        '
    dev_url: https://github.com/chardet/chardet
    doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
    doc_url: http://chardet.readthedocs.org/
    home: https://github.com/chardet/chardet
    license: LGPL2
    license_family: GPL
    license_file: LICENSE
    summary: Universal character encoding detector
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dan-blanchard
        - jschueller
        - nehaljwani
        - sigmavirus24
