# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\singledispatch-feedstock\recipe, last modified Tue Jul  3 15:55:10 2018
# ------------------------------------------------

package:
    name: singledispatch
    version: 3.4.0.3
source:
    fn: singledispatch-3.4.0.3.tar.gz
    md5: af2fc6a3d6cc5a02d0bf54d909785fcb
    url: https://pypi.io/packages/source/s/singledispatch/singledispatch-3.4.0.3.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - six 1.11.0 py37_1
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - singledispatch
about:
    description: 'This library brings functools.singledispatch from Python 3.4 to
        Python

        2.6-3.3.

        '
    doc_source_url: https://github.com/ambv/singledispatch/blob/master/README.rst
    doc_url: http://docs.python.org/3/library/functools.html#functools.singledispatch
    home: http://docs.python.org/3/library/functools.html#functools.singledispatch
    license: MIT
    summary: Transforms a function into a single-dispatch generic function
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
