# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\backcall-feedstock\recipe, last modified Tue Jul  3 15:45:26 2018
# ------------------------------------------------

package:
    name: backcall
    version: 0.1.0
source:
    fn: backcall-0.1.0.tar.gz
    sha256: 38ecd85be2c1e78f77fd91700c76e14667dc21e2713b63876c0eb901196e01e4
    url: https://pypi.io/packages/source/b/backcall/backcall-0.1.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - backcall
about:
    description: 'Backcall provides a way of specifying the parameters that callback
        functions

        need to accept, and adapting callbacks that take fewer parameters, so you

        can add parameters to your callback API without breaking code that doesn''t

        know about them.

        '
    home: https://github.com/takluyver/backcall/
    license: BSD-3-Clause
    license_family: BSD
    summary: Specifications for callback functions passed in to an API
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - takluyver
