# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003isk51i\tmp\build\80754af9\rsync-recipes\zipp-0.3.3-python_3.7-on-winbuilder, last modified Fri Mar 22 12:54:56 2019
# ------------------------------------------------

package:
    name: zipp
    version: 0.3.3
source:
    sha256: 55ca87266c38af6658b84db8cfb7343cdb0bf275f93c7afaea0d8e7a209c7478
    url: https://pypi.io/packages/source/z/zipp/zipp-0.3.3.tar.gz
build:
    noarch: false
    number: '1'
    script: 'C:\ci\zipp_1553291647683\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed -vv '
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - setuptools_scm 3.2.0 py_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - zipp
about:
    dev_url: https://github.com/jaraco/zipp
    doc_url: https://zipp.readthedocs.io/en/latest
    home: https://github.com/jaraco/zipp
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A pathlib-compatible Zipfile object wrapper
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
