# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000029cv55l\tmp\build\80754af9\rsync-recipes\sphinx-1.8.5-python_3.7-on-winbuilder, last modified Mon Mar 11 10:24:49 2019
# ------------------------------------------------

package:
    name: sphinx
    version: 1.8.5
source:
    sha256: c7658aab75c920288a8cf6f09f244c6cfdae30d82d803ac1634d9f223a80ca08
    url: https://pypi.io/packages/source/S/Sphinx/Sphinx-1.8.5.tar.gz
build:
    entry_points:
        - sphinx-apidoc = sphinx.ext.apidoc:main
        - sphinx-autogen = sphinx.ext.autosummary.generate:main
        - sphinx-build = sphinx.cmd.build:main
        - sphinx-quickstart = sphinx.cmd.quickstart:main
    number: '0'
    script:
        - C:\ci\sphinx_1552326775626\_h_env\python.exe -m pip install . --no-deps
            --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.33.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - alabaster >=0.7,<0.8
        - babel >=1.3,!=2.0
        - colorama >=0.3.5
        - docutils >=0.11
        - imagesize
        - jinja2 >=2.3
        - packaging
        - pygments >=2.0
        - python >=3.7,<3.8.0a0
        - requests >=2.0.0
        - setuptools
        - six >=1.5
        - snowballstemmer >=1.1
        - sphinxcontrib-websupport
test:
    commands:
        - sphinx-build -h
        - sphinx-quickstart --version
        - sphinx-quickstart -h
        - sphinx-apidoc -h
        - sphinx-autogen -h
    imports:
        - sphinx
        - sphinx.pycode
about:
    description: 'Sphinx is a tool that makes it easy to create intelligent and beautiful
        documentation,

        written by Georg Brandl and licensed under the BSD license.

        It was originally created for the new Python documentation, and it has excellent

        facilities for the documentation of Python projects, but C/C++ is already
        supported

        as well, and it is planned to add special support for other languages as well.

        '
    dev_url: https://github.com/sphinx-doc/sphinx
    doc_source_url: https://github.com/sphinx-doc/sphinx/blob/master/doc/contents.rst
    doc_url: http://www.sphinx-doc.org/en/stable/contents.html
    home: http://www.sphinx-doc.org
    license: BSD 2-clause
    license_file: LICENSE
    summary: Sphinx is a tool that makes it easy to create intelligent and beautiful
        documentation
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - chohner
        - jakirkham
        - ocefpaf
