# This file created by conda-build 3.8.1
# meta.yaml template originally from:
# C:\ci\containers\00003u64920\tmp\build\80754af9\rsync-recipes\lz4-c-1.8.1.2-c_compiler_vs2015-vc_14-on-winbuilder, last modified Tue Apr 24 12:14:37 2018
# ------------------------------------------------

package:
    name: lz4-c
    version: 1.8.1.2
source:
    fn: lz4-1.8.1.2.tar.gz
    patches:
        - 0001-Do-not-build-tests-binaries-on-VS-project.patch
        - 0002-CMake-include-xxhash.c-in-LZ4_CLI_SOURCES-it-is-buil.patch
        - 0003-CMake-Add-LZ4_DLL_EXPORT-1-LZ4_DLL_IMPORT-1-to-compi.patch
        - 0004-CMake-VC9-disable-various-warnings-that-trip-up-Wind.patch
        - 0005-CMake-Add-datagen-executable.patch
        - 0006-CMake-Set-SHARED-STATIC-IMPORT_LIBRARY_PREFIXes-for-.patch
        - 0007-Makefile-LDFLAGS-must-appear-after-inputs-when-linking.patch
        - 0008-CMake-link-the-CLI-programs-statically-to-the-lib-co.patch
    sha256: 12f3a9e776a923275b2dc78ae138b4967ad6280863b77ff733028ce89b8123f9
    url: https://github.com/lz4/lz4/archive/v1.8.1.2.tar.gz
build:
    number: '0'
    run_exports:
        - lz4-c >=1.8.1.2,<1.9.0a0
    string: h2fa13f4_0
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    run:
        - vc 14.*
test:
    commands:
        - echo on
        - echo %CD%
        - lz4 -h
        - if not exist %LIBRARY_INC%\\lz4.h exit 1
        - if not exist %LIBRARY_INC%\\lz4hc.h exit 1
        - if not exist %LIBRARY_INC%\\lz4frame.h exit 1
        - if not exist %LIBRARY_BIN%\\liblz4.dll exit 1
        - if not exist %LIBRARY_LIB%\\liblz4.lib exit 1
        - if not exist %LIBRARY_LIB%\\liblz4_static.lib exit 1
about:
    description: 'LZ4 is lossless compression algorithm, providing compression speed
        at 400

        MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,

        with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression

        derivative, called LZ4_HC, is available, trading customizable CPU time for

        compression ratio. LZ4 library is provided as open source software using a

        BSD license.

        '
    home: https://www.lz4.org
    license: BSD 2-clause
    license_file: lib/LICENSE
    summary: Extremely Fast Compression algorithm
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - rmax
        - wesm
