# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# C:\ci\containers\00003fqf0nm\tmp\build\80754af9\rsync-recipes\zstd-1.3.7-vc_14-c_compiler_vs2017-on-winbuilder, last modified Mon Nov  5 17:15:06 2018
# ------------------------------------------------

package:
    name: zstd
    version: 1.3.7
source:
    patches:
        - patches/0005-CMake-Fix-windres-.rc-not-including-programs-windres.patch
    sha256: 3277f236df0ca6edae01ae84e865470000c5a3484588fd5bc3d869877fd3573d
    url: https://github.com/facebook/zstd/releases/download/v1.3.7/zstd-1.3.7.tar.gz
build:
    number: '0'
    run_exports:
        - zstd >=1.3.7,<1.3.8.0a0
    string: h508b16e_0
requirements:
    build:
        - cmake 3.12.2 he025d50_0
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    commands:
        - if not exist %LIBRARY_BIN%\libzstd.dll exit 1
        - if not exist %LIBRARY_INC%\zstd.h exit 1
        - if not exist %LIBRARY_LIB%\libzstd.lib exit 1
        - if not exist %LIBRARY_LIB%\libzstd_static.lib exit 1
        - zstd -be -i5
    host:
        - certifi 2018.10.15 py37_0
        - lz4 2.1.2 py37he774522_0
        - lz4-c 1.8.1.2 h2fa13f4_0
        - python 3.7.1 h33f27b4_4
        - setuptools 40.5.0 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
        - xz 5.2.4 h2fa13f4_4
        - zlib 1.2.11 h8395fce_2
    run:
        - vc >=14.1,<15.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    description: 'Zstandard is a real-time compression algorithm, providing high compression

        ratios. It offers a very wide range of compression / speed trade-off, while

        being backed by a very fast decoder. It also offers a special mode for

        small data, called dictionary compression, and can create dictionaries from

        any sample set. Zstandard library is provided as open source software using

        a BSD license.

        '
    dev_url: https://github.com/facebook/zstd
    doc_url: https://facebook.github.io/zstd/zstd_manual.html
    home: http://www.zstd.net
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Zstandard - Fast real-time compression algorithm
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - rmax
