# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# C:\ci\containers\00000nsu9ku\tmp\build\80754af9\rsync-recipes\mpmath-1.1.0-python_3.7-on-winbuilder, last modified Mon Dec 17 14:28:49 2018
# ------------------------------------------------

package:
    name: mpmath
    version: 1.1.0
source:
    fn: mpmath-1.1.0.tar.gz
    sha256: fc17abe05fbab3382b61a123c398508183406fa132e0223874578e20946499f6
    url: https://pypi.io/packages/source/m/mpmath/mpmath-1.1.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - openssl 1.1.1a he774522_0
        - python 3.7.1 h8c8aaf0_6
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - mpmath
        - mpmath.calculus
        - mpmath.functions
        - mpmath.libmp
        - mpmath.matrices
        - mpmath.tests
about:
    description: 'mpmath is a free Python library for real and complex floating-point

        arithmetic with arbitrary precision.

        '
    dev_url: https://github.com/fredrik-johansson/mpmath
    doc_source_url: https://github.com/fredrik-johansson/mpmath/blob/master/doc/source/index.txt
    doc_url: http://mpmath.org/doc/current/
    home: http://mpmath.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Python library for arbitrary-precision floating-point arithmetic
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - msarahan
        - ocefpaf
