# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000001qofbd\tmp\build\80754af9\rsync-recipes\pyzmq-18.0.0-cxx_compiler_vs2017-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Mon Feb 25 17:13:55 2019
# ------------------------------------------------

package:
    name: pyzmq
    version: 18.0.0
source:
    sha256: b30c339eb58355f51f4f54dd61d785f1ff58c86bca1c3a5916977631d121867b
    url: https://pypi.io/packages/source/p/pyzmq/pyzmq-18.0.0.tar.gz
build:
    number: '0'
    string: py37ha925a31_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - libsodium 1.0.16 h9d3ae62_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
        - zeromq 4.3.1 h33f27b4_3
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - zeromq >=4.3.1,<4.4.0a0
test:
    commands:
        - py.test --pyargs zmq.tests.test_socket
    imports:
        - zmq
        - zmq.backend.cython.socket
        - zmq.backend.cython.utils
        - zmq.devices.monitoredqueue
    requires:
        - pytest
about:
    description: 'PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and
        fast

        messaging implementation.

        '
    dev_url: https://github.com/zeromq/pyzmq
    doc_source_url: https://github.com/zeromq/pyzmq/blob/master/docs/source/index.rst
    doc_url: https://pyzmq.readthedocs.org/
    home: https://github.com/zeromq/pyzmq
    license: BSD 3-clause
    license_family: BSD
    summary: Python bindings for zeromq
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - mingwandroid
        - minrk
        - msarahan
        - ocefpaf
        - pelson
