# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-gmp, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-gmp
    version: 6.1.0
source:
    md5: ebf85c5b344d118e70e45b6147663422
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-gmp-6.1.0-1.src.tar.gz
build:
    number: '2'
    string: '2'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
about:
    home: http://gmplib.org/
    license: LGPL3
    summary: A free library for arbitrary precision arithmetic (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: 028dc3e0d92bd5a59c7fb089da67d3e0
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-gmp
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-gmp-6.1.0-1-any.pkg.tar.xz
        win-64:
            md5: 820243e6e54f51e81bbd43849efc46ac
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-gmp
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-gmp-6.1.0-1-any.pkg.tar.xz
