# This file created by conda-build 3.17.7
# meta.yaml template originally from:
# C:\ci\containers\000001skdrk\tmp\build\80754af9\rsync-recipes\blosc-1.15.0-vc_14-cxx_compiler_vs2017-c_compiler_vs2017-on-winbuilder, last modified Thu Jan 17 14:45:21 2019
# ------------------------------------------------

package:
    name: blosc
    version: 1.15.0
source:
    sha256: dbbb01f9fedcdf2c2ff73296353a9253f44ce9de89c081cbd8146170dce2ba8f
    url: https://github.com/Blosc/c-blosc/archive/v1.15.0.tar.gz
build:
    number: '0'
    run_exports:
        - blosc >=1.15.0,<2.0a0
    string: h7bd577a_0
requirements:
    build:
        - cmake 3.12.2 he025d50_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - snappy 1.1.7 h777316e_3
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - snappy >=1.1.7,<2.0a0
        - vc >=14.1,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - IF NOT EXIST %LIBRARY_INC%/blosc.h exit 1
        - IF NOT EXIST %LIBRARY_INC%/blosc-export.h exit 1
        - IF NOT EXIST %LIBRARY_BIN%/blosc.dll exit 1
        - IF NOT EXIST %LIBRARY_LIB%/blosc.lib exit 1
about:
    home: https://github.com/Blosc/c-blosc
    license: BSD 3-Clause
    license_file: LICENSES/BLOSC.txt
    summary: A blocking, shuffling and loss-less compression library that can be faster
        than `memcpy()`
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - FrancescElies
        - danielfrg
        - jakirkham
        - msarahan
