# This file created by conda-build 3.14.4
# meta.yaml template originally from:
# C:\ci\containers\00001766rlg\tmp\build\80754af9\rsync-recipes\olefile-0.46-python_3.7-on-winbuilder, last modified Tue Sep 11 15:17:56 2018
# ------------------------------------------------

package:
    name: olefile
    version: '0.46'
source:
    sha256: 133b031eaf8fd2c9399b78b8bc5b8fcbe4c31e85295749bb17a87cba8f3c3964
    url: https://pypi.io/packages/source/o/olefile/olefile-0.46.zip
build:
    noarch: false
    number: '0'
    script: C:\ci\olefile_1536697574408\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - olefile
about:
    description: 'Python package to parse, read and write Microsoft OLE2 files

        (Structured Storage or Compound Document, Microsoft Office) -

        Improved version of the OleFileIO module from PIL, the Python

        Image Library.

        '
    dev_url: https://github.com/decalage2/olefile
    doc_source_url: https://github.com/decalage2/olefile/blob/master/doc/index.rst
    doc_url: http://olefile.readthedocs.io/en/latest/index.html
    home: http://www.decalage.info/python/olefileio
    license: BSD 2-Clause
    license_family: BSD
    license_file: doc/License.rst
    summary: parse, read and write Microsoft OLE2 files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - decarlof
        - dgursoy
        - ericdill
        - licode
        - ocefpaf
        - ravescovi
        - tacaswell
