# This file created by conda-build 3.16.0
# meta.yaml template originally from:
# C:\ci\containers\00003f294k9\tmp\build\80754af9\rsync-recipes\testpath-0.4.2-python_3.7-on-winbuilder, last modified Sat Oct  6 17:17:32 2018
# ------------------------------------------------

package:
    name: testpath
    version: 0.4.2
source:
    sha256: b694b3d9288dbd81685c5d2e7140b81365d46c29f5db4bc659de5aa6b98780f8
    url: https://pypi.io/packages/source/t/testpath/testpath-0.4.2.tar.gz
build:
    number: '0'
    script: C:\ci\testpath_1538864661240\_h_env\python.exe -m pip install . --no-deps
        --no-build-isolation --ignore-installed -vvv
    string: py37_0
requirements:
    host:
        - certifi 2018.8.24 py37_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 40.4.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.0 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - testpath
about:
    description: 'Testpath contains functions to check things on the filesystem,

        and tools for mocking system commands and recording calls to those.

        '
    dev_url: https://github.com/jupyter/testpath
    doc_url: https://testpath.readthedocs.io
    home: https://testpath.readthedocs.io
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Testpath is a collection of utilities for Python code working with files
        and commands.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
        - takluyver
