# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003isk51e\tmp\build\80754af9\rsync-recipes\dask-1.1.4-python_3.7-on-winbuilder, last modified Fri Mar 22 13:28:53 2019
# ------------------------------------------------

package:
    name: dask
    version: 1.1.4
source:
    fn: dask-1.1.4.tar.gz
    sha256: 7e9a3c053d8f503483d7357d5b8486c70250c4975b08b3d29f91ab7fc97736c3
    url: https://pypi.io/packages/source/d/dask/dask-1.1.4.tar.gz
build:
    noarch: false
    number: '1'
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - openssl 1.1.1b he774522_1
        - python 3.7.2 h8c8aaf0_10
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - bokeh >=0.13.0
        - cloudpickle >=0.2.1
        - cytoolz >=0.7.3
        - dask-core 1.1.4.*
        - distributed >=1.26.0
        - numpy >=1.11.0
        - pandas >=0.19.0
        - partd >=0.3.8
        - python >=3.7,<3.8.0a0
        - toolz >=0.7.3
test:
    imports:
        - dask
        - dask.array
        - dask.bag
        - dask.bytes
        - dask.dataframe
        - dask.dataframe.tseries
        - dask.delayed
        - dask.diagnostics
        - dask.distributed
        - distributed
about:
    description: 'Dask is a flexible parallel computing library for analytic computing.

        '
    dev_url: https://github.com/dask/dask
    doc_source_url: https://github.com/dask/dask/blob/master/docs/source/index.rst
    doc_url: https://dask.pydata.org/
    home: http://github.com/dask/dask/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Parallel Python with task scheduling
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - alimanfoo
        - jakirkham
        - jcrist
        - koverholt
        - martindurant
        - mingwandroid
        - mrocklin
        - pitrou
        - shoyer
        - tomaugspurger
