# This file created by conda-build 3.17.6
# meta.yaml template originally from:
# C:\ci\containers\00002gc3h3m\tmp\build\80754af9\rsync-recipes\numexpr-2.6.9-blas_impl_mkl-cxx_compiler_vs2017-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Fri Jan 11 15:44:12 2019
# ------------------------------------------------

package:
    name: numexpr
    version: 2.6.9
source:
    sha256: fc218b777cdbb14fa8cff8f28175ee631bacabbdd41ca34e061325b6c44a6fa6
    url: https://pypi.io/packages/source/n/numexpr/numexpr-2.6.9.tar.gz
build:
    number: '0'
    script:
        - copy %PREFIX%\\site.cfg site.cfg
        - dos2unix numexpr/*.py
        - dos2unix numexpr/tests/*.py
        - C:\\ci\\numexpr_1547243302999\\_h_env\\python.exe setup.py install --single-version-externally-managed
            --record=record.txt
    string: py37hdce8814_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.1 144
        - mkl 2019.1 144
        - mkl-devel 2019.1 145
        - mkl-include 2019.1 144
        - numpy-base 1.15.4 py37hc3f5095_0
        - numpy-devel 1.15.4 py37h4ba5984_0
        - openssl 1.1.1a he774522_0
        - python 3.7.2 h8c8aaf0_0
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - blas 1.0 mkl
        - mkl >=2019.1,<2020.0a0
        - numpy >=1.15.4,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - numexpr
        - numexpr.interpreter
    requires:
        - setuptools
about:
    description: 'Numexpr is a fast numerical expression evaluator for NumPy. With
        it,

        expressions that operate on arrays (like "3*a+4*b") are accelerated and use

        less memory than doing the same calculation in Python.

        '
    dev_url: https://github.com/pydata/numexpr
    doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
    home: https://github.com/pydata/numexpr
    license: MIT
    license_file: LICENSE.txt
    summary: Fast numerical expression evaluator for NumPy.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - djkirkham
        - msarahan
        - ocefpaf
        - scopatz
