# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\msys2-conda-epoch, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: msys2-conda-epoch
    version: '20160418'
build:
    number: '1'
    string: '1'
requirements:
    build: []
    run: []
