# This file created by conda-build 3.17.7
# meta.yaml template originally from:
# C:\ci\containers\00002gc3h8g\tmp\build\80754af9\rsync-recipes\bleach-3.1.0-python_3.7-on-winbuilder, last modified Thu Jan 17 12:36:29 2019
# ------------------------------------------------

package:
    name: bleach
    version: 3.1.0
source:
    sha256: 3fdf7f77adcf649c9911387df51254b813185e32b2c6619f690b593a617e19fa
    url: https://pypi.io/packages/source/b/bleach/bleach-3.1.0.tar.gz
build:
    noarch: false
    number: '0'
    script: C:\ci\bleach_1547750576988\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 18.1 py37_0
        - python 3.7.2 h8c8aaf0_0
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
        - six
        - webencodings
test:
    imports:
        - bleach
about:
    description: 'Bleach is an allowed-list-based HTML sanitizing library that escapes
        or

        strips markup and attributes.

        '
    dev_url: https://github.com/mozilla/bleach
    doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst
    doc_url: https://bleach.readthedocs.io/
    home: https://github.com/mozilla/bleach
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Easy, whitelist-based HTML-sanitizing tool
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
