# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# C:\ci\containers\00000pm59bs\tmp\build\80754af9\rsync-recipes\sortedcontainers-2.1.0-python_3.7-on-winbuilder, last modified Fri Nov 30 16:42:38 2018
# ------------------------------------------------

package:
    name: sortedcontainers
    version: 2.1.0
source:
    fn: sortedcontainers-2.1.0.tar.gz
    sha256: 974e9a32f56b17c1bac2aebd9dcf197f3eb9cd30553c5852a3187ad162e1a03a
    url: https://pypi.io/packages/source/s/sortedcontainers/sortedcontainers-2.1.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - openssl 1.1.1a he774522_0
        - python 3.7.1 he44a216_5
        - setuptools 40.6.2 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - sortedcontainers
about:
    description: 'SortedContainers is a sorted collections library, written in pure-Python

        and fast as C-extensions.

        '
    dev_url: https://github.com/grantjenks/sorted_containers/
    doc_source_url: https://github.com/grantjenks/sorted_containers/blob/master/docs/index.rst
    doc_url: http://www.grantjenks.com/docs/sortedcontainers/
    home: http://www.grantjenks.com/docs/sortedcontainers/
    license: Apache 2.0
    summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - grantjenks
        - msarahan
        - nehaljwani
        - richafrank
