# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000001qofav\tmp\build\80754af9\rsync-recipes\pluggy-0.9.0-python_3.7-on-winbuilder, last modified Mon Feb 25 17:14:16 2019
# ------------------------------------------------

package:
    name: pluggy
    version: 0.9.0
source:
    fn: pluggy-0.9.0.tar.gz
    sha256: 19ecf9ce9db2fce065a7a0586e07cfb4ac8614fe96edf628a264b1c70116cf8f
    url: https://pypi.io/packages/source/p/pluggy/pluggy-0.9.0.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install . --no-deps --ignore-installed
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 19.0.1 py37_0
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - setuptools_scm 3.2.0 py_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - pluggy
about:
    dev_url: https://github.com/pytest-dev/pluggy/
    doc_url: https://pluggy.readthedocs.io/en/latest/
    home: https://github.com/pytest-dev/pluggy
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Plugin registration and hook calling for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohnGreeley
        - nicoddemus
        - tgoodlet
