# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-gcc-libgfortran, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-gcc-libgfortran
    version: 5.3.0
source:
    md5: 4698350ad11d86459ffc4843fe1c951f
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-gcc-libgfortran-5.3.0-5.src.tar.gz
build:
    number: '6'
    string: '6'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-gcc-libs-core
about:
    home: https://gcc.gnu.org
    license: GPL, LGPL, FDL, custom
    summary: GNU Compiler Collection (libgfortran) for MinGW-w64
extra:
    msys2-binaries:
        win-32:
            md5: 55031f066d5c6ab9caa96de590ffb8be
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-gcc-libgfortran
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-gcc-libgfortran-5.3.0-5-any.pkg.tar.xz
        win-64:
            md5: 79b96eb048ea42b30538a665c6469e97
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-gcc-libgfortran
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-gcc-libgfortran-5.3.0-5-any.pkg.tar.xz
