# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002g6vms8\tmp\build\80754af9\rsync-recipes\xlwings-0.15.4-python_3.7-on-winbuilder, last modified Mon Mar 18 11:24:13 2019
# ------------------------------------------------

package:
    name: xlwings
    version: 0.15.4
source:
    fn: xlwings-0.15.4.tar.gz
    sha256: ad760e15e74ff2b44cca87d453a940f7da1a6dc121be21660ea42a5f3ae9f13e
    url: https://pypi.io/packages/source/x/xlwings/xlwings-0.15.4.tar.gz
build:
    entry_points:
        - xlwings = xlwings.command_line:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - openssl 1.1.1b he774522_1
        - python 3.7.2 h8c8aaf0_10
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wincertstore 0.2 py37_0
    run:
        - comtypes
        - python >=3.7,<3.8.0a0
        - pywin32
test:
    commands:
        - xlwings -h
    imports:
        - xlwings
        - xlwings.conversion
about:
    description: 'xlwings is a BSD-licensed Python library that makes it easy to call
        Python from Excel and vice versa.

        '
    dev_url: https://github.com/ZoomerAnalytics/xlwings
    doc_source_url: https://github.com/ZoomerAnalytics/xlwings/blob/master/docs/quickstart.rst
    doc_url: http://docs.xlwings.org/en/stable/index.html
    home: http://xlwings.org/
    license: 3-clause BSD
    license_family: BSD
    license_file: LICENSE.txt
    summary: Interact with Excel from Python and vice versa
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - fzumstein
        - nirajd
