# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# C:\ci\containers\000014eb0ka\tmp\build\80754af9\rsync-recipes\zlib-1.2.11-c_compiler_vs2017-vc_14-on-winbuilder, last modified Wed Nov 21 09:40:06 2018
# ------------------------------------------------

package:
    name: zlib
    version: 1.2.11
source:
    fn: zlib-1.2.11.tar.gz
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: http://zlib.net/zlib-1.2.11.tar.gz
build:
    number: '3'
    run_exports:
        - zlib >=1.2.11,<1.3.0a0
    string: h62dcd97_3
requirements:
    build:
        - cmake 3.12.2 he025d50_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - vc >=14.1,<15.0a0
about:
    description: 'zlib is designed to be a free, general-purpose, lossless data-compression

        library for use on virtually any computer hardware and operating system.

        '
    dev_url: https://github.com/madler/zlib
    doc_url: http://zlib.net/manual.html
    home: http://zlib.net/
    license: zlib
    license_family: Other
    license_file: license.txt
    summary: Massively spiffy yet delicately unobtrusive compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - groutr
        - mingwandroid
        - msarahan
        - ocefpaf
