# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\backports.shutil_get_terminal_size-feedstock\recipe, last modified Tue Jul  3 15:45:29 2018
# ------------------------------------------------

package:
    name: backports.shutil_get_terminal_size
    version: 1.0.0
source:
    fn: backports.shutil_get_terminal_size-1.0.0.tar.gz
    sha256: 713e7a8228ae80341c70586d1cc0a8caa5207346927e23d09dcbcaf18eadec80
    url: https://pypi.io/packages/source/b/backports.shutil_get_terminal_size/backports.shutil_get_terminal_size-1.0.0.tar.gz
build:
    number: '2'
    script: pip install --no-deps .
    string: py37_2
requirements:
    host:
        - backports 1.0 py37_1
        - certifi 2018.4.16 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - backports
        - python >=3.7,<3.8.0a0
test:
    imports:
        - backports
        - backports.shutil_get_terminal_size
about:
    home: https://github.com/chrippa/backports.shutil_get_terminal_size
    license: MIT
    license_file: LICENSE
    summary: A backport of the get_terminal_size function from Python 3.3's shutil.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
